SELECT DEPT.NAME, STDDEV_POP(DEPT.DEPTNO), AVG(DEPT.DEPTNO), STDDEV_SAMP(DEPT.DEPTNO), VAR_POP(DEPT.DEPTNO), VAR_SAMP(DEPT.DEPTNO) FROM DEPT AS DEPT GROUP BY DEPT.NAME
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10) AS t WHERE t.DEPTNO + 5 > t.EMPNO
SELECT EMP.JOB, EMP.EMPNO, EMP.SAL, SUM(EMP.SAL) AS S FROM EMP AS EMP WHERE EMP.EMPNO = 10 GROUP BY EMP.JOB, EMP.EMPNO, EMP.SAL
SELECT EMP.EMPNO, (((SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20))) AS D FROM EMP AS EMP
