SELECT UNIX_TIMESTAMP('12:34:56') FROM EMP AS EMP
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 INTERSECT SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20) AS t1 INTERSECT SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30
SELECT R.Z + R.X FROM ( SELECT U.X + U.Y AS Z, U.X FROM ( SELECT * FROM (VALUES (10, 1), (30, 3)) AS T(X, Y) WHERE X + Y > 50) AS U) AS R
SELECT * FROM ( SELECT * FROM (VALUES (10, 1), (30, 3)) AS T(X, Y) UNION ALL SELECT * FROM (VALUES (20, 2)) ) AS R WHERE X + Y > 30
SELECT DEPT.DEPTNO, DEPT.DEPTNO AS DEPTNO0 FROM DEPT AS DEPT ORDER BY DEPT.DEPTNO LIMIT 10000 OFFSET 1
SELECT DEPT.DEPTNO, DEPT.DEPTNO AS DEPTNO0 FROM DEPT AS DEPT ORDER BY DEPT.DEPTNO LIMIT 10000 OFFSET 1
SELECT DEPT.DEPTNO, DEPT.DEPTNO FROM DEPT AS DEPT ORDER BY DEPT.DEPTNO LIMIT 10000 OFFSET 1
SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 7 AND EMP.EMPNO = 10 AND EMP.MGR IS NULL AND EMP.EMPNO = 10
SELECT * FROM EMP AS EMP WHERE EMP.EMPNO + 10 / 2 = 13
SELECT EMP.ENAME FROM EMP AS EMP, DEPT AS DEPT, EMP AS EMP0 WHERE EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DEPTNO = EMP0.DEPTNO
SELECT t.ENAME, COUNT(t.MGR) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.ENAME
SELECT COUNT(*), SUM(EMPNO) FROM EMP WHERE FALSE
SELECT 4, 2 + 3, MAX(5) FROM EMP AS EMP GROUP BY 4, 2 + 3
SELECT A + B AS X, B, A FROM (VALUES (10, 1), (30, 7), (20, 3)) AS T(A, B) WHERE A - B < 21
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 EXCEPT SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20) AS t1 EXCEPT SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30
SELECT * FROM EMP AS EMP WHERE EXISTS (SELECT * FROM EMP AS EMP0 WHERE EMP.DEPTNO = EMP0.DEPTNO) AND NOT EXISTS (SELECT * FROM EMP AS EMP1 WHERE EMP1.JOB = EMP.JOB AND EMP1.SAL = 34)
SELECT * FROM (VALUES (30, 3)) AS T (X, Y) WHERE X > 30 EXCEPT SELECT * FROM (VALUES (20, 2)) EXCEPT SELECT * FROM (VALUES (40, 4))
SELECT t.EXPR$0 + t.EXPR$1 FROM (VALUES  (10, 1),  (20, 3)) AS t
SELECT COUNT(*) AS C FROM EMP AS EMP WHERE EMP.DEPTNO = 10 GROUP BY EMP.DEPTNO, EMP.SAL
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EXISTS (SELECT * FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20) AND EMP.SAL < 100
SELECT * FROM (VALUES  (10, 'x'),  (20, 'y')) AS t WHERE t.EXPR$0 < 15
SELECT DEPT.DEPTNO FROM DEPT AS DEPT WHERE DEPT.DEPTNO = 7 AND DEPT.DEPTNO = 8
SELECT EMP.DEPTNO AS X, SUM(EMP.SAL), EMP.EMPNO AS Y FROM EMP AS EMP GROUP BY EMP.DEPTNO, EMP.EMPNO
SELECT EMP.ENAME FROM EMP AS EMP, DEPT AS DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO
SELECT 2, EMP.DEPTNO, EMP.JOB FROM EMP AS EMP UNION ALL SELECT 2, EMP0.DEPTNO, EMP0.JOB FROM EMP AS EMP0
SELECT * FROM EMP WHERE EMPNO NOT IN (SELECT EMPNO FROM (SELECT ENAME, EMPNO, SAL AS R FROM EMP) AS t WHERE R > 2 AND EMP.ENAME = ENAME)
SELECT * FROM (SELECT CASE WHEN EMP.SAL > 1000 THEN NULL ELSE FALSE END AS CASECOL FROM EMP AS EMP) AS t WHERE NOT t.CASECOL
SELECT EMP.SAL, SUM(EMP.COMM), MIN(EMP.COMM), SUM(DISTINCT EMP.SAL) FROM EMP AS EMP GROUP BY EMP.SAL
SELECT EMP.SAL FROM EMP AS EMP WHERE EMP.EMPNO NOT IN (SELECT DEPT.DEPTNO FROM DEPT AS DEPT WHERE EMP.JOB = DEPT.NAME)
SELECT * FROM (SELECT t2.NAME, t2.DEPTNO FROM (SELECT DEPT.NAME, DEPT.DEPTNO, COUNT(*) FROM DEPT AS DEPT GROUP BY DEPT.NAME, DEPT.DEPTNO EXCEPT ALL SELECT DEPT0.NAME, DEPT0.DEPTNO, 1 FROM DEPT AS DEPT0) AS t2 EXCEPT ALL SELECT t7.NAME, t7.DEPTNO FROM (SELECT DEPT1.NAME, DEPT1.DEPTNO, 1 FROM DEPT AS DEPT1 EXCEPT ALL SELECT DEPT2.NAME, DEPT2.DEPTNO, COUNT(*) FROM DEPT AS DEPT2 GROUP BY DEPT2.NAME, DEPT2.DEPTNO) AS t7) AS t9 EXCEPT ALL SELECT DEPT3.NAME, DEPT3.DEPTNO FROM DEPT AS DEPT3
SELECT EMP.SAL FROM EMP AS EMP WHERE EMP.EMPNO IN (SELECT DEPT.DEPTNO FROM DEPT AS DEPT WHERE EMP.JOB = DEPT.NAME)
SELECT COUNT(1) FROM EMP WHERE CAST(NULL AS INTEGER) = 1
SELECT EMP.DEPTNO, COUNT(DISTINCT EMP.ENAME), COUNT(DISTINCT EMP.JOB) FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT DEPT.DEPTNO, DEPT.NAME FROM DEPT AS DEPT INNER JOIN (SELECT EMP.DEPTNO AS DEPTNO9 FROM EMP AS EMP WHERE EMP.SAL > 100 GROUP BY EMP.DEPTNO) AS T1 ON DEPT.DEPTNO = T1.DEPTNO9
SELECT T.ENAME FROM (SELECT EMP.ENAME, EMP.DEPTNO, EMP.SAL + 1 AS SALPLUS FROM EMP AS EMP) AS T WHERE T.DEPTNO IN (SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.SAL + 1 = EMP0.JOB)
SELECT EMP.EMPNO FROM EMP AS EMP WHERE (EMP.EMPNO, EMP.DEPTNO) IN (SELECT EMP0.EMPNO, EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20) OR EMP.SAL < 100
SELECT t0.ENAME, t0.SAL, t0.DEPTNO FROM (SELECT EMP.ENAME, EMP.SAL, EMP.DEPTNO FROM EMP AS EMP) AS t0 WHERE t0.SAL > 5000 GROUP BY t0.ENAME, t0.SAL, t0.DEPTNO
SELECT * FROM ANON AS t WHERE 1 + 2 > 3 + NULL
SELECT 1 FROM (SELECT EMP.DEPTNO, COUNT(*) FROM EMP AS EMP WHERE EMP.DEPTNO > 7 GROUP BY EMP.DEPTNO) AS t1 INNER JOIN EMP AS EMP0 ON t1.DEPTNO = EMP0.DEPTNO INNER JOIN EMP AS EMP1 ON EMP0.DEPTNO = EMP1.DEPTNO
SELECT EMP.MGR FROM EMP AS EMP WHERE EMP.MGR = 10
SELECT * FROM EMP AS EMP WHERE EMP.SAL = 4 OR EMP.EMPNO NOT IN (SELECT DEPT.DEPTNO FROM DEPT AS DEPT)
SELECT 1 FROM (SELECT EMP.COMM AS DEPTNO FROM EMP AS EMP WHERE EMP.DEPTNO > 7) AS t0 INNER JOIN EMP AS EMP0 ON t0.DEPTNO = EMP0.DEPTNO
SELECT * FROM EMP AS EMP WHERE EXISTS (SELECT * FROM EMP AS EMP0 WHERE EMP.DEPTNO = EMP0.DEPTNO)
SELECT 1 FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO > 7) AS t INNER JOIN EMP AS EMP0 ON t.DEPTNO = EMP0.DEPTNO INNER JOIN EMP AS EMP1 ON EMP0.DEPTNO = EMP1.DEPTNO
SELECT t.ENAME, COUNT(*) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.ENAME
SELECT EMP.ENAME FROM EMP AS EMP, DEPT AS DEPT, EMP AS EMP0 WHERE EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DEPTNO = EMP0.DEPTNO
SELECT * FROM T AS T WHERE T.F0_C0 IN (SELECT T0.F1_C0 AS C0 FROM T AS T0)
SELECT * FROM (VALUES (FALSE),(TRUE)) AS Q (COL1) WHERE NOT(COL1)
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END FROM EMP AS EMP INNER JOIN BONUS AS BONUS ON EMP.ENAME = BONUS.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END
SELECT EMP.JOB, MIN(EMP.SAL) AS MIN_SAL, MIN(EMP.DEPTNO) AS MIN_DEPTNO, SUM(EMP.SAL) + 1 AS SUM_SAL_PLUS, MAX(EMP.SAL) AS MAX_SAL, SUM(EMP.SAL) AS SUM_SAL_2, COUNT(*) AS COUNT_SAL, COUNT(EMP.MGR) AS COUNT_MGR FROM EMP AS EMP INNER JOIN DEPT AS DEPT ON EMP.JOB = DEPT.NAME GROUP BY EMP.JOB, DEPT.NAME
SELECT 1 FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO > 7) AS t INNER JOIN EMP AS EMP0 ON t.DEPTNO = EMP0.DEPTNO
SELECT t.ENAME, AVG(t.EMPNO) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.ENAME
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END FROM EMP AS EMP FULL JOIN BONUS AS BONUS ON EMP.ENAME = BONUS.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END
SELECT * FROM (SELECT UPPER(SUBSTRING(X FROM 1 FOR 2) || SUBSTRING(X FROM 3)) AS U, SUBSTRING(X FROM 1 FOR 1) AS S FROM (SELECT 'table' AS X FROM (VALUES (TRUE)) AS T0 UNION SELECT 'view' FROM (VALUES (TRUE)) AS T1 UNION SELECT 'foreign table' FROM (VALUES (TRUE)) AS T2) AS T3) AS T4 WHERE U = 'TABLE'
SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 7 AND EMP.DEPTNO = 8 AND EMP.EMPNO = 10 AND EMP.MGR IS NULL AND EMP.EMPNO = 10
SELECT * FROM (SELECT * FROM (SELECT NULL AS N FROM EMP AS EMP) AS t WHERE t.N IS NULL AND t.N IS NULL) AS t0 WHERE t0.N IS NULL
SELECT t1.DEPTNO, COUNT(*) FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 UNION ALL SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO > 20) AS t1 GROUP BY t1.DEPTNO
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EMP.EMPNO > 10 AND EMP.EMPNO <= 10
SELECT t.DEPTNO, t.JOB, SUM(t.EMPNO), COUNT(*), MIN(t.DEPTNO), MAX(t.EMPNO) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.DEPTNO, t.JOB
SELECT EMP.ENAME FROM EMP AS EMP, DEPT AS DEPT, EMP AS EMP0 WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.EMPNO = EMP0.EMPNO
SELECT 1 FROM EMP AS EMP INNER JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT t.NAME, SUM(EMP.SAL) AS SUM_SAL, COUNT(*) AS C FROM EMP AS EMP INNER JOIN (SELECT DEPT.NAME FROM DEPT AS DEPT GROUP BY DEPT.NAME) AS t ON EMP.JOB = t.NAME GROUP BY t.NAME
SELECT 1 FROM EMP AS EMP FULL JOIN EMP AS EMP0 ON EMP.DEPTNO = EMP0.DEPTNO WHERE EMP.DEPTNO > 7 AND EMP0.DEPTNO > 9
SELECT EMP.SAL FROM EMP AS EMP WHERE EMP.EMPNO IN (SELECT DEPT.DEPTNO FROM DEPT AS DEPT WHERE EMP.JOB = DEPT.NAME) AND EMP.EMPNO IN (SELECT EMP0.EMPNO FROM EMP AS EMP0 WHERE EMP.ENAME = EMP0.ENAME)
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END FROM BONUS AS BONUS LEFT JOIN EMP AS EMP ON BONUS.ENAME = EMP.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EXISTS (SELECT * FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20)
SELECT EMP.DEPTNO, MAX(EMP.MGR) FROM EMP AS EMP GROUP BY 42 + 24, EMP.DEPTNO
SELECT t.ENAME, SUM(t.EMPNO), COUNT(*), MIN(t.DEPTNO), MAX(t.EMPNO) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.ENAME
SELECT * FROM (SELECT EMP.ENAME, RANK() OVER (PARTITION BY EMP.DEPTNO ORDER BY EMP.SAL RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS R FROM EMP AS EMP) AS t WHERE t.R < 2
SELECT t.DEPTNO, t.JOB, SUM(t.MGR) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.DEPTNO, t.JOB
SELECT t.NAME FROM (SELECT * FROM DEPT AS DEPT WHERE DEPT.DEPTNO = 10) AS t WHERE t.DEPTNO = 10
SELECT EMP.DEPTNO, EMP.JOB, COUNT(DISTINCT EMP.ENAME) FROM EMP AS EMP GROUP BY EMP.DEPTNO, EMP.JOB
SELECT EMP.DEPTNO, EMP.JOB, COUNT(DISTINCT EMP.ENAME), SUM(EMP.SAL) FROM EMP AS EMP GROUP BY EMP.DEPTNO, EMP.JOB
SELECT t.SAL FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t
SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 EXCEPT SELECT * FROM (SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20 EXCEPT SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30) AS t2
SELECT DEPT.NAME AS DNAME, COUNT(*) AS C FROM DEPT AS DEPT GROUP BY DEPT.NAME HAVING DEPT.NAME = 'Charlie'
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END FROM EMP AS EMP FULL JOIN BONUS AS BONUS ON EMP.ENAME = BONUS.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END
SELECT * FROM ( SELECT * FROM EMP WHERE FALSE) AS E JOIN DEPT AS D ON E.DEPTNO = D.DEPTNO
SELECT * FROM EMP AS EMP WHERE FALSE ORDER BY EMP.DEPTNO
SELECT EMP.SAL, SUM(EMP.COMM), MIN(DISTINCT EMP.COMM), SUM(DISTINCT EMP.SAL) FROM EMP AS EMP GROUP BY EMP.SAL
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EMP.EMPNO = 10 AND EMP.EMPNO IS NULL
SELECT 1 FROM EMP AS EMP INNER JOIN (SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO > 7) AS t ON EMP.DEPTNO = t.DEPTNO
SELECT t.DEPTNO, t.JOB, COUNT(t.MGR) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.DEPTNO, t.JOB
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END FROM EMP AS EMP RIGHT JOIN BONUS AS BONUS ON EMP.ENAME = BONUS.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END FROM BONUS AS BONUS RIGHT JOIN EMP AS EMP ON BONUS.ENAME = EMP.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END
SELECT DEPT.DEPTNO, DEPT.NAME FROM DEPT AS DEPT RIGHT JOIN (SELECT EMP.DEPTNO FROM EMP AS EMP WHERE EMP.SAL > 100 GROUP BY EMP.DEPTNO) AS t1 ON DEPT.DEPTNO = t1.DEPTNO
SELECT 1 FROM DEPT AS DEPT FULL JOIN EMP AS EMP ON DEPT.DEPTNO = EMP.DEPTNO WHERE EMP.SAL > 100
SELECT DEPT.NAME AS C1 FROM DEPT AS DEPT WHERE DEPT.NAME > 'b' GROUP BY DEPT.NAME HAVING DEPT.NAME > 'c' AND (COUNT(*) > 30 OR DEPT.NAME < 'z')
SELECT COUNT(*) FROM EMP JOIN DEPT ON JOB = NAME
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END FROM EMP AS EMP LEFT JOIN BONUS AS BONUS ON EMP.ENAME = BONUS.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END
SELECT * FROM (SELECT DEPT.NAME FROM DEPT AS DEPT UNION ALL SELECT DEPT0.NAME FROM DEPT AS DEPT0) AS T1 ORDER BY T1.NAME FETCH NEXT 10 ROWS ONLY
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EMP.EMPNO = 10 AND NOT EMP.EMPNO = 10
SELECT t.ENAME, TRIM( BOTH ' ' FROM t.JOB ), t.SAL * 2, t.DEPTNO FROM ( SELECT EMP.ENAME, TRIM( BOTH ' ' FROM EMP.JOB ) AS JOB, EMP.SAL * 2 AS SAL, EMP.DEPTNO FROM EMP AS EMP ) AS t, DEPT AS DEPT WHERE t.DEPTNO = DEPT.DEPTNO
SELECT * FROM (SELECT EMP.ENAME, (RANK() OVER (PARTITION BY EMP.DEPTNO ORDER BY EMP.SAL RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) + 1 AS R FROM EMP AS EMP) AS t WHERE t.R < 2
SELECT CASE WHEN 1 = 2 THEN t0.EXPR$0 ELSE 2 END FROM (VALUES  (1)) AS t LEFT JOIN (VALUES  (1)) AS t0(EXPR$0) ON TRUE
SELECT SUM(t.c) FROM ANON AS t
SELECT * FROM EMP AS EMP LEFT JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO ORDER BY EMP.SAL FETCH NEXT 10 ROWS ONLY
SELECT EMP.* FROM EMP AS EMP RIGHT JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO ORDER BY DEPT.NAME
SELECT * FROM EMP AS EMP LEFT JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO ORDER BY EMP.SAL, DEPT.NAME LIMIT 10
SELECT EMP.* FROM EMP AS EMP RIGHT JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO ORDER BY DEPT.NAME
SELECT * FROM EMP AS EMP RIGHT JOIN (SELECT * FROM DEPT AS DEPT LIMIT 10) AS t ON EMP.DEPTNO = t.DEPTNO LIMIT 10
SELECT * FROM (SELECT DEPT.NAME, DEPT.DEPTNO FROM DEPT AS DEPT UNION ALL SELECT t4.NAME, t4.DEPTNO FROM (SELECT DEPT0.NAME, DEPT0.DEPTNO, COUNT(*) FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME, DEPT0.DEPTNO UNION ALL SELECT DEPT1.NAME, DEPT1.DEPTNO, COUNT(*) FROM DEPT AS DEPT1 GROUP BY DEPT1.NAME, DEPT1.DEPTNO) AS t4) AS t6 UNION ALL SELECT DEPT2.NAME, DEPT2.DEPTNO FROM DEPT AS DEPT2
SELECT DEPT.DEPTNO, DEPT.NAME FROM DEPT AS DEPT INNER JOIN (SELECT EMP.DEPTNO FROM EMP AS EMP WHERE EMP.SAL > 100 GROUP BY EMP.DEPTNO) AS T1 ON DEPT.DEPTNO = T1.DEPTNO
SELECT S.DEPTNO FROM (SELECT *   FROM DEPT   WHERE EXISTS (     SELECT * FROM EMP     WHERE EMP.DEPTNO = DEPT.DEPTNO     AND EMP.SAL > 100)) S JOIN ACCOUNT ON S.DEPTNO = ACCOUNT.ACCTNO
SELECT 1 FROM EMP AS EMP INNER JOIN EMP AS EMP0 ON EMP.DEPTNO = EMP0.DEPTNO
SELECT A + B AS X, B, A FROM (VALUES (10, 1), (30, 7)) AS T(A, B) WHERE A - B < 0
SELECT EMP.EMPNO + EMP.DEPTNO FROM EMP AS EMP WHERE EMP.SAL = 10 * EMP.COMM AND UPPER(EMP.ENAME) = 'FOO'
SELECT EMP.DEPTNO, SUM(EMP.COMM), MIN(EMP.COMM), SUM(DISTINCT EMP.SAL) FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT EMP.DEPTNO AS X, SUM(EMP.SAL), EMP.EMPNO AS Y FROM EMP AS EMP GROUP BY EMP.DEPTNO, EMP.EMPNO
SELECT DEPT.* FROM DEPT AS DEPT INNER JOIN (SELECT EMP.DEPTNO FROM EMP AS EMP) AS t ON DEPT.DEPTNO = t.DEPTNO WHERE DEPT.DEPTNO <= 10
SELECT T.ENAME, MIN(T.EMPNO) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS T GROUP BY T.ENAME
SELECT T1.DEPTNO, T1.JOB, SUM(T1.U) FROM (SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, EMP.DEPTNO, EMP.SLACKER, 2 AS U FROM EMP AS EMP UNION ALL SELECT EMP0.EMPNO, EMP0.ENAME, EMP0.JOB, EMP0.MGR, EMP0.HIREDATE, EMP0.SAL, EMP0.COMM, EMP0.DEPTNO, EMP0.SLACKER, 3 AS U FROM EMP AS EMP0) AS T1 GROUP BY T1.DEPTNO, T1.JOB
SELECT DEPT.DEPTNO, DEPT.NAME, COUNT(*) AS C FROM DEPT AS DEPT GROUP BY DEPT.DEPTNO, DEPT.NAME HAVING DEPT.NAME = 'Charlie'
SELECT DEPT.NAME AS DNAME, DEPT.DEPTNO AS DDEPTNO, COUNT(*) AS C FROM DEPT AS DEPT GROUP BY DEPT.NAME, DEPT.DEPTNO HAVING DEPT.NAME = 'Charlie'
SELECT 1 FROM (SELECT * FROM (SELECT EMP.DEPTNO FROM EMP AS EMP WHERE EMP.DEPTNO > 7 UNION ALL SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.DEPTNO > 10) AS t3 UNION ALL SELECT EMP1.DEPTNO FROM EMP AS EMP1 WHERE EMP1.DEPTNO > 1) AS t6 INNER JOIN EMP AS EMP2 ON t6.DEPTNO = EMP2.DEPTNO
SELECT DEPT.NAME, STDDEV_POP(DEPT.DEPTNO), AVG(DEPT.DEPTNO), STDDEV_SAMP(DEPT.DEPTNO), VAR_POP(DEPT.DEPTNO), VAR_SAMP(DEPT.DEPTNO) FROM DEPT AS DEPT GROUP BY DEPT.NAME
SELECT EMP.DEPTNO, MAX(EMP.MGR) FROM EMP AS EMP GROUP BY EMP.DEPTNO, 4
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 INTERSECT SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20) AS t1 INTERSECT ALL SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE FALSE) AS T RIGHT JOIN DEPT AS DEPT ON T.DEPTNO = DEPT.DEPTNO
SELECT 1 FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO > 7) AS t LEFT JOIN EMP AS EMP0 ON t.DEPTNO = EMP0.DEPTNO WHERE EMP0.DEPTNO > 9
SELECT t.DEPTNO, t.JOB, MAX(t.MGR) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.DEPTNO, t.JOB
SELECT CASE WHEN NULL IS NULL THEN 2 IS NULL WHEN 2 IS NULL THEN NULL IS NULL ELSE NULL = 2 END FROM (VALUES  (0)) AS t
SELECT EMP.SAL FROM EMP AS EMP, (SELECT * FROM EMP AS EMP0 UNION ALL SELECT * FROM EMP AS EMP1) AS T
SELECT 1 FROM DEPT AS DEPT LEFT JOIN EMP AS EMP ON DEPT.DEPTNO = EMP.DEPTNO WHERE DEPT.NAME = 'Charlie' AND EMP.SAL > 100
SELECT t.DEPTNO, t.JOB, AVG(t.EMPNO) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.DEPTNO, t.JOB
SELECT EMP.SAL FROM EMP AS EMP WHERE CASE WHEN EMP.SAL = 1000 THEN NULL ELSE 1 END IS NULL OR CASE WHEN EMP.SAL = 2000 THEN NULL ELSE 1 END IS NULL
SELECT DEPT.NAME, MAX(DEPT.NAME), AVG(DEPT.DEPTNO), MIN(DEPT.NAME) FROM DEPT AS DEPT GROUP BY DEPT.NAME
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 UNION ALL SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20) AS t1 UNION ALL SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30
SELECT t1.NAME, t1.EMPNO FROM (SELECT t.DEPTNO, t.NAME, t0.EMPNO, t0.ENAME, t0.JOB, t0.MGR, t0.HIREDATE, t0.SAL, t0.COMM, t0.DEPTNO AS DEPTNO1, t0.SLACKER FROM (SELECT DEPT.DEPTNO, DEPT.NAME, DEPT.DEPTNO AS DEPTNO0 FROM DEPT AS DEPT) AS t INNER JOIN (SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, EMP.DEPTNO, EMP.SLACKER, EMP.DEPTNO AS DEPTNO0 FROM EMP AS EMP) AS t0 ON t.DEPTNO0 = t0.DEPTNO0) AS t1 WHERE t1.JOB = 'Manager'
SELECT 1 FROM DEPT AS DEPT LEFT JOIN EMP AS EMP ON DEPT.DEPTNO = EMP.DEPTNO WHERE EMP.SAL > 100
SELECT SUM(t.MGR) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t
SELECT * FROM (SELECT * FROM (SELECT * FROM (VALUES  (30, 3)) AS t EXCEPT SELECT * FROM (VALUES  (20, 2)) AS t0 WHERE t0.EXPR$0 > 30) AS t2 EXCEPT SELECT * FROM (VALUES  (40, 4)) AS t3) AS t4 EXCEPT SELECT * FROM (VALUES  (50, 5)) AS t5 WHERE t5.EXPR$0 > 50
SELECT t.JOB, DEPT.NAME FROM (SELECT * FROM EMP AS EMP WHERE EMP.EMPNO = 10) AS t INNER JOIN DEPT AS DEPT ON t.JOB = DEPT.NAME GROUP BY t.JOB, DEPT.NAME
SELECT t0.JOB, t1.NAME FROM (SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, EMP.DEPTNO, EMP.SLACKER, EMP.DEPTNO + EMP.EMPNO AS $f9 FROM EMP AS EMP WHERE EMP.EMPNO = 10) AS t0 INNER JOIN (SELECT DEPT.DEPTNO, DEPT.NAME, DEPT.DEPTNO + 5 AS $f2 FROM DEPT AS DEPT) AS t1 ON t0.JOB = t1.NAME AND t0.$f9 = t1.$f2 GROUP BY t0.JOB, t1.NAME
SELECT t.EMPNO, DEPT.DEPTNO AS DEPTNO0 FROM (SELECT * FROM EMP AS EMP WHERE EMP.EMPNO = 10) AS t INNER JOIN DEPT AS DEPT ON t.EMPNO = DEPT.DEPTNO GROUP BY t.EMPNO, DEPT.DEPTNO
SELECT EMP.DEPTNO FROM EMP AS EMP INNER JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO GROUP BY EMP.DEPTNO
SELECT EMP.DEPTNO, DEPT.DEPTNO AS DEPTNO0 FROM EMP AS EMP INNER JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO GROUP BY EMP.DEPTNO, DEPT.DEPTNO
SELECT 1+2, D.DEPTNO+(3+4), (5+6)+D.DEPTNO, CAST(NULL AS INTEGER), COALESCE(2,NULL), ROW(7+8) FROM DEPT D INNER JOIN EMP E ON D.DEPTNO = E.DEPTNO + (5-5) WHERE D.DEPTNO=(7+8) AND D.DEPTNO=(8+7) AND D.DEPTNO=COALESCE(2,NULL)
SELECT t1.ENAME, SUM(t1.U) FROM (SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, EMP.DEPTNO, EMP.SLACKER, NULL AS U FROM EMP AS EMP UNION ALL SELECT EMP0.EMPNO, EMP0.ENAME, EMP0.JOB, EMP0.MGR, EMP0.HIREDATE, EMP0.SAL, EMP0.COMM, EMP0.DEPTNO, EMP0.SLACKER, NULL AS U FROM EMP AS EMP0) AS t1 GROUP BY t1.ENAME
SELECT t.ENAME FROM (SELECT DEPT.DEPTNO, EMP.ENAME FROM EMP AS EMP INNER JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DEPTNO = 10) AS t WHERE t.DEPTNO = 10
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 UNION SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20) AS t1 UNION SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30
SELECT * FROM DEPT AS DEPT LEFT JOIN EMP AS EMP ON DEPT.DEPTNO = EMP.DEPTNO WHERE EMP.DEPTNO IS NOT NULL AND EMP.SAL > 100
SELECT T.JOB, SUM(T.SAL) FROM (SELECT * FROM EMP AS EMP WHERE EMP.EMPNO = 10) AS T INNER JOIN DEPT AS DEPT ON T.JOB = DEPT.NAME GROUP BY T.JOB, DEPT.NAME
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EMP.DEPTNO IN (SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20) OR EMP.SAL < 100
SELECT COUNT(*) FROM EMP AS EMP WHERE CASE WHEN EMP.DEPTNO = 20 THEN 2 WHEN EMP.DEPTNO = 10 THEN 1 ELSE 3 END = 1
SELECT 1 FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 7 OR EMP.DEPTNO = 9 OR EMP.COMM > 10) AS t INNER JOIN EMP AS EMP0 ON t.DEPTNO = EMP0.DEPTNO
SELECT U.Z + U.X FROM ( SELECT R.X + R.Y AS Z, R.X FROM ( SELECT * FROM (VALUES (10, 1), (30, 3)) AS T(X, Y) WHERE X + Y > 50) AS R ) AS U
SELECT 1 FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 7 OR EMP.DEPTNO = 9 OR EMP.DEPTNO > 10) AS t INNER JOIN EMP AS EMP0 ON t.DEPTNO = EMP0.DEPTNO
SELECT EMP.DEPTNO, MAX(EMP.ENAME) FROM EMP AS EMP GROUP BY EMP.DEPTNO, 4
SELECT * FROM DEPT AS DEPT UNION SELECT * FROM DEPT AS DEPT0
SELECT EMP.ENAME FROM EMP AS EMP, DEPT AS DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.ENAME = 'foo'
SELECT t3.DEPTNO, t3.JOB FROM (SELECT EMP.DEPTNO, EMP.JOB FROM EMP AS EMP GROUP BY EMP.DEPTNO, EMP.JOB UNION ALL SELECT EMP0.DEPTNO, EMP0.JOB FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO, EMP0.JOB) AS t3 GROUP BY t3.DEPTNO, t3.JOB
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10) AS t WHERE t.DEPTNO + 5 > t.EMPNO
SELECT t.ENAME, SUM(t.MGR) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.ENAME
SELECT SUM(EMPNO) FROM EMP WHERE FALSE GROUP BY DEPTNO
SELECT 1 FROM (SELECT EMP.COMM AS DEPTNO FROM EMP AS EMP WHERE EMP.COMM > 7) AS t0 INNER JOIN EMP AS EMP0 ON t0.DEPTNO = EMP0.DEPTNO
SELECT 1 FROM (SELECT EMP.DEPTNO, COUNT(*) FROM EMP AS EMP WHERE EMP.DEPTNO > 7 GROUP BY EMP.DEPTNO) AS t1 INNER JOIN EMP AS EMP0 ON t1.DEPTNO = EMP0.DEPTNO
SELECT * FROM EMP AS EMP ORDER BY EMP.DEPTNO FETCH NEXT 0 ROWS ONLY
SELECT t0.NAME, SUM(DISTINCT t0.CN), SUM(DISTINCT t0.SM) FROM (SELECT DEPT.NAME, COUNT(*) AS CN, SUM(DEPT.DEPTNO) AS SM FROM DEPT AS DEPT GROUP BY DEPT.NAME) AS t0 GROUP BY t0.NAME
SELECT EMP.DEPTNO, COUNT(DISTINCT EMP.ENAME) FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT EMP.DEPTNO, COUNT(DISTINCT EMP.ENAME), SUM(EMP.SAL) FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT COUNT(DISTINCT EMP.DEPTNO), SUM(EMP.SAL) FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT EMP.EMPNO, EMP.DEPTNO IN (SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20) AS D FROM EMP AS EMP
SELECT EMP.DEPTNO, EMP.ENAME, CASE WHEN 1 = 2 THEN SUBSTRING(EMP.ENAME FROM 1 FOR 2) ELSE NULL END FROM EMP AS EMP GROUP BY EMP.DEPTNO, EMP.ENAME, CASE WHEN 1 = 2 THEN SUBSTRING(EMP.ENAME FROM 1 FOR 2) ELSE NULL END
SELECT t.DEPTNO, t.JOB, COUNT(*) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.DEPTNO, t.JOB
SELECT EMP.EMPNO, COUNT(*), AVG(DISTINCT DEPT.DEPTNO) FROM EMP AS EMP INNER JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO GROUP BY EMP.EMPNO
SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 UNION SELECT * FROM (SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20 INTERSECT SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30) AS t2
SELECT EMP.DEPTNO, SUM(EMP.DEPTNO), SUM(DISTINCT EMP.SAL), MAX(EMP.DEPTNO), MAX(EMP.COMM) FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT EMP.DEPTNO, COUNT(*), SUM(DISTINCT EMP.SAL) FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EMP.EMPNO = 10 AND EMP.EMPNO IS NOT NULL
SELECT t.DEPTNO, t.JOB, MIN(t.EMPNO) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.DEPTNO, t.JOB
SELECT 4, 2 + 3, MAX(EMP.MGR) FROM EMP AS EMP GROUP BY 4, 2 + 3
SELECT EMP.DEPTNO, MAX(EMP.MGR) FROM EMP AS EMP GROUP BY EMP.DEPTNO, 4, 2 + 3, EMP.DEPTNO + 42
SELECT * FROM (VALUES (30, 3)) INTERSECT SELECT * FROM (VALUES (10, 1), (30, 3)) AS T (X, Y) WHERE X > 50 INTERSECT SELECT * FROM (VALUES (30, 3))
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END FROM BONUS AS BONUS RIGHT JOIN EMP AS EMP ON BONUS.ENAME = EMP.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END
SELECT EMP.DEPTNO, EMP.DEPTNO + 1, EMP.EMPNO + EMP.DEPTNO FROM EMP AS EMP WHERE EMP.DEPTNO = 10
SELECT * FROM (SELECT EMP.DEPTNO FROM EMP AS EMP WHERE EMP.DEPTNO < 4) AS t0 INNER JOIN (SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.DEPTNO > 7 UNION ALL SELECT EMP1.DEPTNO FROM EMP AS EMP1) AS t4 ON t0.DEPTNO = t4.DEPTNO
SELECT * FROM EMP AS EMP WHERE (EMP.EMPNO, EMP.DEPTNO) IN (SELECT EMP0.EMPNO, EMP0.DEPTNO FROM EMP AS EMP0 GROUP BY EMP0.EMPNO, EMP0.DEPTNO) OR EMP.DEPTNO < 40 + 60
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 INTERSECT SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20) AS t1 INTERSECT SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30
SELECT T1.ENAME, SUM(T1.U) FROM (SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, EMP.DEPTNO, EMP.SLACKER, 2 AS U FROM EMP AS EMP UNION ALL SELECT EMP0.EMPNO, EMP0.ENAME, EMP0.JOB, EMP0.MGR, EMP0.HIREDATE, EMP0.SAL, EMP0.COMM, EMP0.DEPTNO, EMP0.SLACKER, 3 AS U FROM EMP AS EMP0) AS T1 GROUP BY T1.ENAME
SELECT 1 FROM EMP AS EMP INNER JOIN DEPT AS DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT EMP.EMPNO, EXISTS (SELECT * FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20) AS D FROM EMP AS EMP
SELECT EMP.ENAME FROM EMP AS EMP, DEPT AS DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.ENAME = 'foo'
SELECT 1 FROM DEPT AS DEPT RIGHT JOIN EMP AS EMP ON DEPT.DEPTNO = EMP.DEPTNO WHERE DEPT.NAME = 'Charlie'
SELECT EMP.DEPTNO, COUNT(DISTINCT EMP.DEPTNO, EMP.JOB) AS CDDJ, SUM(EMP.SAL) AS S FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT DEPT.DEPTNO, EMP.DEPTNO AS DEPTNO0 FROM DEPT AS DEPT, EMP AS EMP WHERE DEPT.DEPTNO + 10 = EMP.DEPTNO * 2
SELECT EMP.ENAME FROM EMP AS EMP, EMP AS EMP0, DEPT AS DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.DEPTNO = EMP0.DEPTNO AND DEPT.NAME = 'foo'
SELECT 1 FROM DEPT AS DEPT FULL JOIN EMP AS EMP ON DEPT.DEPTNO = EMP.DEPTNO WHERE DEPT.NAME = 'Charlie'
SELECT EMP.DEPTNO, MAX(EMP.MGR) FROM EMP AS EMP GROUP BY 4, EMP.DEPTNO
SELECT 1 FROM (SELECT EMP.DEPTNO FROM EMP AS EMP WHERE EMP.DEPTNO > 7 UNION ALL SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.DEPTNO > 10) AS t3 INNER JOIN EMP AS EMP1 ON t3.DEPTNO = EMP1.DEPTNO
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.EMPNO = 10) AS t LEFT JOIN DEPT AS DEPT ON t.EMPNO = DEPT.DEPTNO
SELECT COUNT(*) FROM EMP AS EMP WHERE CASE WHEN EMP.DEPTNO = 20 THEN 2 WHEN EMP.DEPTNO = 10 THEN 1 ELSE NULL END = 1
SELECT COUNT(*) FROM EMP AS EMP WHERE CASE WHEN EMP.DEPTNO = 30 THEN 1 WHEN EMP.DEPTNO = 20 THEN 2 WHEN EMP.DEPTNO = 10 THEN 1 WHEN EMP.DEPTNO = 30 THEN 111 ELSE 0 END = 1
SELECT EMP.EMPNO FROM EMP AS EMP LEFT JOIN DEPT AS DEPT ON (((SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20))) < (((SELECT EMP1.DEPTNO FROM EMP AS EMP1 WHERE EMP1.EMPNO > 100)))
SELECT 4, 2 + 3, MAX(5) FROM EMP AS EMP GROUP BY 4, 2 + 3
SELECT 1 FROM DEPT AS DEPT LEFT JOIN EMP AS EMP ON DEPT.DEPTNO = EMP.DEPTNO
SELECT T.SAL FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS T, EMP AS EMP1
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 UNION ALL SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20) AS t1 UNION SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30
SELECT EMP.DEPTNO FROM EMP AS EMP GROUP BY EMP.DEPTNO HAVING COUNT(*) > 1
SELECT * FROM (VALUES (1,2)) WHERE 1 + 2 > 3 + CAST(NULL AS INTEGER)
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EXISTS (SELECT * FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20) OR EMP.SAL < 100
SELECT EMP.JOB, EMP.EMPNO, EMP.SAL, SUM(EMP.SAL) AS S FROM EMP AS EMP WHERE EMP.EMPNO = 10 GROUP BY EMP.JOB, EMP.EMPNO, EMP.SAL
SELECT EMP.MGR FROM EMP AS EMP WHERE CASE WHEN EMP.MGR < 10 THEN TRUE ELSE FALSE END
SELECT t0.SAL FROM (SELECT * FROM (SELECT EMP.SAL, EMP.DEPTNO FROM EMP AS EMP) AS t WHERE t.DEPTNO = 200) AS t0 INNER JOIN (SELECT t1.DEPTNO FROM (SELECT EMP0.SAL, EMP0.DEPTNO FROM EMP AS EMP0) AS t1 WHERE t1.SAL = 100) AS t3 ON t0.DEPTNO = t3.DEPTNO
SELECT EMP.EMPNO, (((SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20))) AS D FROM EMP AS EMP
SELECT COUNT(DISTINCT EMP.ENAME), COUNT(DISTINCT EMP.JOB) FROM EMP AS EMP
WITH E2 AS (   SELECT EMPNO, CASE WHEN TRUE THEN DEPTNO ELSE NULL END AS DEPTNO   FROM EMP) SELECT EMPNO,   DEPTNO IN (SELECT DEPTNO FROM E2 WHERE EMPNO < 20) AS D FROM E2
SELECT t0.ENAME, t0.SAL, t0.DEPTNO FROM (SELECT EMP.ENAME, EMP.SAL, EMP.DEPTNO FROM EMP AS EMP) AS t0 WHERE t0.SAL > 5000 GROUP BY t0.ENAME, t0.SAL, t0.DEPTNO
SELECT COUNT(*) AS C FROM EMP AS EMP WHERE EMP.DEPTNO = 10 GROUP BY EMP.DEPTNO
SELECT EMP.JOB FROM EMP AS EMP WHERE EMP.SAL IS NULL AND EMP.JOB = 'Clerk' GROUP BY EMP.SAL, EMP.JOB HAVING COUNT(*) > 3
SELECT t0.EMPNO, t0.ENAME, t0.JOB, t0.MGR, t0.HIREDATE, t0.SAL, t0.COMM, t0.DEPTNO, t0.SLACKER, t1.DEPTNO AS DEPTNO0, t1.NAME FROM (SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, EMP.DEPTNO, EMP.SLACKER, EMP.DEPTNO + EMP.EMPNO AS $f9 FROM EMP AS EMP WHERE EMP.EMPNO = 10) AS t0 INNER JOIN (SELECT DEPT.DEPTNO, DEPT.NAME, DEPT.DEPTNO + 5 AS $f2 FROM DEPT AS DEPT) AS t1 ON t0.EMPNO = t1.DEPTNO AND t0.$f9 = t1.$f2
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END FROM EMP AS EMP INNER JOIN BONUS AS BONUS ON EMP.ENAME = BONUS.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN -1 * EMP.SAL ELSE EMP.SAL END
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END FROM BONUS AS BONUS LEFT JOIN EMP AS EMP ON BONUS.ENAME = EMP.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END
SELECT DEPT.DEPTNO, DEPT.NAME FROM DEPT AS DEPT FULL JOIN (SELECT EMP.DEPTNO FROM EMP AS EMP WHERE EMP.SAL > 100 GROUP BY EMP.DEPTNO) AS t1 ON DEPT.DEPTNO = t1.DEPTNO
SELECT DEPT.NAME FROM DEPT AS DEPT LEFT JOIN (SELECT EMP.DEPTNO FROM EMP AS EMP WHERE EMP.SAL > 100 GROUP BY EMP.DEPTNO) AS t1 ON DEPT.DEPTNO = t1.DEPTNO
SELECT EMP.EMPNO, (EMP.EMPNO, EMP.DEPTNO) IN (SELECT EMP0.EMPNO, EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20) AS D FROM EMP AS EMP
SELECT * FROM (   SELECT * FROM EMP WHERE FALSE) E LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO
SELECT EMP.SAL FROM EMP AS EMP WHERE CASE WHEN EMP.SAL = 1000 THEN CASE WHEN EMP.SAL = 1000 THEN NULL ELSE 1 END IS NULL ELSE CASE WHEN EMP.SAL = 2000 THEN NULL ELSE 1 END IS NULL END IS TRUE
SELECT 1 FROM EMP AS EMP RIGHT JOIN (SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO > 9) AS t ON EMP.DEPTNO = t.DEPTNO WHERE EMP.DEPTNO > 7
SELECT EMP.DEPTNO, COUNT(DISTINCT EMP.ENAME) AS CDE, COUNT(DISTINCT EMP.JOB, EMP.ENAME) AS CDJE, COUNT(DISTINCT EMP.DEPTNO, EMP.JOB) AS CDDJ, SUM(EMP.SAL) AS S FROM EMP AS EMP GROUP BY EMP.DEPTNO
SELECT DEPTNO, JOB, SUM(U) FROM (SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER, CAST(NULL AS INTEGER) AS U FROM EMP UNION ALL SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER, CAST(NULL AS INTEGER) AS U FROM EMP) AS t1 GROUP BY ROLLUP(DEPTNO, JOB)
SELECT EMP.EMPNO FROM EMP AS EMP WHERE EMP.EMPNO < CASE WHEN EMP.DEPTNO IN (SELECT CASE WHEN TRUE THEN EMP0.DEPTNO ELSE NULL END FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20) = TRUE THEN 10 WHEN EMP.DEPTNO IN (SELECT CASE WHEN TRUE THEN EMP1.DEPTNO ELSE NULL END FROM EMP AS EMP1 WHERE EMP1.EMPNO < 20) = FALSE THEN 20 ELSE 30 END
SELECT * FROM (SELECT DEPT.NAME FROM DEPT AS DEPT UNION ALL SELECT DEPT0.NAME FROM DEPT AS DEPT0) AS T1 ORDER BY T1.NAME
SELECT * FROM (SELECT DEPT.NAME FROM DEPT AS DEPT UNION ALL SELECT DEPT0.NAME FROM DEPT AS DEPT0) AS T1 ORDER BY T1.NAME FETCH NEXT 0 ROWS ONLY
SELECT 1 FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO > 7 AND EMP.COMM = EMP.DEPTNO AND EMP.COMM + EMP.DEPTNO > EMP.COMM / 2) AS t INNER JOIN (SELECT * FROM EMP AS EMP0 WHERE EMP0.SAL = EMP0.DEPTNO) AS t0 ON t.DEPTNO = t0.DEPTNO
SELECT EMP.EMPNO FROM EMP AS EMP WHERE (((SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.EMPNO < 20))) < (((SELECT EMP1.DEPTNO FROM EMP AS EMP1 WHERE EMP1.EMPNO > 100))) OR EMP.SAL < 100
SELECT * FROM (VALUES (1,2)) WHERE FALSE
SELECT t.ENAME, MAX(t.MGR) FROM (SELECT * FROM EMP AS EMP UNION ALL SELECT * FROM EMP AS EMP0) AS t GROUP BY t.ENAME
SELECT 2, EMP.DEPTNO, EMP.JOB FROM EMP AS EMP UNION ALL SELECT 1, EMP0.DEPTNO, EMP0.JOB FROM EMP AS EMP0
SELECT 2, 3 FROM EMP AS EMP UNION ALL SELECT 2, 3 FROM EMP AS EMP0
SELECT COUNT(*), CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END FROM EMP AS EMP RIGHT JOIN BONUS AS BONUS ON EMP.ENAME = BONUS.ENAME GROUP BY CASE WHEN EMP.SAL < 11 THEN 11 ELSE -1 * EMP.SAL END
SELECT * FROM (SELECT * FROM EMP AS EMP WHERE EMP.DEPTNO = 10 UNION SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 20) AS t1 UNION ALL SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 30
