SELECT UNIX_TIMESTAMP('12:34:56') FROM EMP AS EMP0
SELECT t10.EMPNO, t10.ENAME, t10.JOB, t10.MGR, t10.HIREDATE, t10.SAL, t10.COMM, t10.DEPTNO, t10.SLACKER FROM (SELECT EMP2.EMPNO, EMP2.ENAME, EMP2.JOB, EMP2.MGR, EMP2.HIREDATE, EMP2.SAL, EMP2.COMM, EMP2.DEPTNO, EMP2.SLACKER, COUNT(*) AS $f9 FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 GROUP BY EMP2.EMPNO, EMP2.ENAME, EMP2.JOB, EMP2.MGR, EMP2.HIREDATE, EMP2.SAL, EMP2.COMM, EMP2.DEPTNO, EMP2.SLACKER UNION ALL SELECT EMP3.EMPNO, EMP3.ENAME, EMP3.JOB, EMP3.MGR, EMP3.HIREDATE, EMP3.SAL, EMP3.COMM, EMP3.DEPTNO, EMP3.SLACKER, COUNT(*) AS $f9 FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 GROUP BY EMP3.EMPNO, EMP3.ENAME, EMP3.JOB, EMP3.MGR, EMP3.HIREDATE, EMP3.SAL, EMP3.COMM, EMP3.DEPTNO, EMP3.SLACKER UNION ALL SELECT EMP4.EMPNO, EMP4.ENAME, EMP4.JOB, EMP4.MGR, EMP4.HIREDATE, EMP4.SAL, EMP4.COMM, EMP4.DEPTNO, EMP4.SLACKER, COUNT(*) AS $f9 FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30 GROUP BY EMP4.EMPNO, EMP4.ENAME, EMP4.JOB, EMP4.MGR, EMP4.HIREDATE, EMP4.SAL, EMP4.COMM, EMP4.DEPTNO, EMP4.SLACKER) AS t10 GROUP BY t10.EMPNO, t10.ENAME, t10.JOB, t10.MGR, t10.HIREDATE, t10.SAL, t10.COMM, t10.DEPTNO, t10.SLACKER HAVING COUNT(*) = 3
SELECT * FROM (VALUES (NULL)) AS t(EXPR$0) WHERE 1 = 0
SELECT * FROM (VALUES (30, 3)) AS T(X, Y)
SELECT DEPTNO, DEPTNO AS DEPTNO0 FROM (SELECT * FROM DEPT ORDER BY DEPTNO LIMIT 10000 OFFSET 1) t0 ORDER BY DEPTNO
SELECT DEPTNO, DEPTNO AS DEPTNO0 FROM (SELECT * FROM DEPT ORDER BY DEPTNO LIMIT 10000 OFFSET 1) t0 ORDER BY DEPTNO
SELECT DEPT0.DEPTNO, DEPT0.DEPTNO FROM DEPT AS DEPT0 ORDER BY DEPT0.DEPTNO LIMIT 10000 OFFSET 1
SELECT 10 AS EMPNO, EMP0.ENAME, EMP0.JOB, NULL AS MGR, EMP0.HIREDATE, EMP0.SAL, EMP0.COMM, 7 AS DEPTNO, EMP0.SLACKER FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 7 AND EMP0.MGR IS NULL AND EMP0.EMPNO = 10
SELECT * FROM EMP AS EMP0 WHERE EMP0.EMPNO + 5 = 13
SELECT T0.ENAME FROM (SELECT * FROM EMP AS EMP1 WHERE EXISTS (SELECT 1 FROM DEPT AS DEPT0 WHERE EMP1.DEPTNO = DEPT0.DEPTNO)) AS T0 INNER JOIN (SELECT * FROM DEPT AS DEPT1 WHERE EXISTS (SELECT 1 FROM EMP AS EMP2 WHERE DEPT1.DEPTNO = EMP2.DEPTNO)) AS T1 ON T0.DEPTNO = T1.DEPTNO INNER JOIN EMP AS EMP3 ON T1.DEPTNO = EMP3.DEPTNO
SELECT t6.ENAME, SUM(sum1) FROM (SELECT EMP1.ENAME, COUNT(EMP1.MGR) as sum1 FROM EMP AS EMP1 GROUP BY EMP1.ENAME UNION ALL SELECT EMP2.ENAME, COUNT(EMP2.MGR) FROM EMP AS EMP2 GROUP BY EMP2.ENAME) AS t6 GROUP BY t6.ENAME
SELECT * FROM (VALUES (0, NULL)) AS t(EXPR$0, EXPR$1)
SELECT 4, 2 + 3, MAX(5) FROM EMP AS EMP0 GROUP BY 4
SELECT * FROM (VALUES (11, 1, 10), (23, 3, 20)) AS t(X, B, A)
SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 EXCEPT SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 EXCEPT SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30
SELECT EMP2.EMPNO, EMP2.ENAME, EMP2.JOB, EMP2.MGR, EMP2.HIREDATE, EMP2.SAL, EMP2.COMM, EMP2.DEPTNO, EMP2.SLACKER FROM EMP AS EMP2 INNER JOIN (SELECT EMP3.DEPTNO, 1 AS $f1 FROM EMP AS EMP3 GROUP BY EMP3.DEPTNO) AS t5 ON EMP2.DEPTNO = t5.DEPTNO LEFT JOIN (SELECT EMP4.JOB, 1 AS $f1 FROM EMP AS EMP4 WHERE EMP4.SAL = 34 GROUP BY EMP4.JOB) AS t10 ON EMP2.JOB = t10.JOB WHERE t10.$f1 IS NULL
SELECT * FROM (SELECT NULL AS X, NULL AS Y) AS t WHERE 1 = 0
SELECT * FROM (VALUES  (11),  (23)) AS t1
SELECT COUNT(*) AS C FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 10 GROUP BY EMP0.SAL
SELECT EMP1.EMPNO FROM EMP AS EMP1, (SELECT 1 AS i FROM EMP AS EMP2 WHERE EMP2.EMPNO < 20 GROUP BY TRUE) AS t4 WHERE EMP1.SAL < 100
SELECT * FROM (VALUES  (10, 'x')) AS t1
SELECT DEPTNO FROM (VALUES (NULL, NULL)) AS t(DEPTNO, NAME) WHERE 1 = 0
SELECT EMP0.DEPTNO AS X, SUM(EMP0.SAL), EMP0.EMPNO AS Y FROM EMP AS EMP0 GROUP BY EMP0.EMPNO, EMP0.DEPTNO
SELECT EMP0.ENAME FROM EMP AS EMP0 INNER JOIN DEPT AS DEPT0 ON EMP0.DEPTNO = DEPT0.DEPTNO
SELECT 2, t6.DEPTNO, t6.JOB FROM (SELECT EMP1.DEPTNO, EMP1.JOB FROM EMP AS EMP1 UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB FROM EMP AS EMP2) AS t6
SELECT EMP.EMPNO, EMP.ENAME, EMP.JOB, EMP.MGR, EMP.HIREDATE, EMP.SAL, EMP.COMM, EMP.DEPTNO, EMP.SLACKER FROM EMP LEFT JOIN (SELECT COUNT(*) AS c, COUNT(*) AS ck, ENAME FROM (SELECT ENAME, EMPNO, SAL AS R FROM EMP) AS t WHERE R > 2 GROUP BY ENAME) AS t3 ON EMP.ENAME = t3.ENAME LEFT JOIN (SELECT EMPNO, TRUE AS i, ENAME FROM (SELECT ENAME, EMPNO, SAL AS R FROM EMP) AS t4 WHERE R > 2) AS t6 ON EMP.EMPNO = t6.EMPNO AND EMP.ENAME = t6.ENAME WHERE t3.c = 0 OR (t6.i IS NOT NULL OR t3.ck < t3.c) IS NOT TRUE
SELECT * FROM (SELECT CASE WHEN EMP0.SAL > 1000 THEN NULL ELSE FALSE END AS CASECOL FROM EMP AS EMP0) AS t1 WHERE NOT t1.CASECOL
SELECT t2.SAL, SUM(t2.sum1), MIN(t2.min1), SUM(t2.SAL) FROM (SELECT EMP0.SAL, SUM(EMP0.COMM) as sum1, MIN(EMP0.COMM) as min1 FROM EMP AS EMP0 GROUP BY EMP0.SAL) AS t2 GROUP BY t2.SAL
SELECT EMP0.SAL FROM EMP AS EMP0 LEFT JOIN (SELECT DEPT0.NAME, COUNT(*) AS c, COUNT(DEPT0.DEPTNO) AS ck FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME) AS t4 ON EMP0.JOB = t4.NAME LEFT JOIN (SELECT DEPT1.DEPTNO, 1 AS i, DEPT1.NAME FROM DEPT AS DEPT1) AS t5 ON EMP0.EMPNO = t5.DEPTNO AND EMP0.JOB = t5.NAME WHERE NOT CASE WHEN t4.c = 0 THEN FALSE WHEN t5.i IS NOT NULL THEN TRUE WHEN t4.ck < t4.c THEN TRUE ELSE FALSE END
SELECT DEPT4.NAME, DEPT4.DEPTNO FROM DEPT AS DEPT4 GROUP BY DEPT4.NAME, DEPT4.DEPTNO EXCEPT ALL SELECT DEPT5.NAME, DEPT5.DEPTNO FROM DEPT AS DEPT5 EXCEPT ALL SELECT * FROM (SELECT DEPT6.NAME, DEPT6.DEPTNO FROM DEPT AS DEPT6 EXCEPT ALL SELECT DEPT7.NAME, DEPT7.DEPTNO FROM DEPT AS DEPT7 GROUP BY DEPT7.NAME, DEPT7.DEPTNO) AS t22 EXCEPT ALL SELECT DEPT8.NAME, DEPT8.DEPTNO FROM DEPT AS DEPT8
SELECT EMP0.SAL FROM EMP AS EMP0 INNER JOIN DEPT AS DEPT0 ON EMP0.JOB = DEPT0.NAME AND EMP0.EMPNO = DEPT0.DEPTNO
SELECT COUNT(*) FROM (SELECT NULL AS EMPNO, NULL AS ENAME, NULL AS JOB, NULL AS MGR, NULL AS HIREDATE, NULL AS SAL, NULL AS COMM, NULL AS DEPTNO, NULL AS SLACKER) AS t WHERE 1 = 0
SELECT DEPTNO, COUNT(ENAME) FILTER (WHERE $g_1), COUNT(JOB) FILTER (WHERE $g_2) FROM (SELECT DEPTNO, ENAME, JOB, GROUPING(DEPTNO, ENAME, JOB) = 1 AS $g_1, GROUPING(DEPTNO, ENAME, JOB) = 2 AS $g_2 FROM EMP GROUP BY GROUPING SETS((ENAME, DEPTNO), (JOB, DEPTNO))) AS t1 GROUP BY DEPTNO
SELECT * FROM DEPT WHERE EXISTS (SELECT 1 FROM (SELECT DEPTNO AS DEPTNO9 FROM EMP WHERE SAL > 100) AS t0 WHERE DEPT.DEPTNO = t0.DEPTNO9)
SELECT t.ENAME FROM (SELECT ENAME, DEPTNO, SAL + 1 AS SALPLUS FROM EMP) AS t INNER JOIN (SELECT DEPTNO FROM EMP WHERE SAL + 1 = JOB GROUP BY DEPTNO) AS t2 ON t.DEPTNO = t2.DEPTNO
SELECT EMP1.EMPNO FROM EMP AS EMP1 LEFT JOIN (SELECT EMP2.EMPNO, EMP2.DEPTNO, 1 AS i FROM EMP AS EMP2 WHERE EMP2.EMPNO < 20) AS t5 ON EMP1.EMPNO = t5.EMPNO AND EMP1.DEPTNO = t5.DEPTNO WHERE t5.i IS NOT NULL OR EMP1.SAL < 100
SELECT t4.ENAME, t4.SAL, t4.DEPTNO FROM (SELECT EMP0.ENAME, EMP0.SAL, EMP0.DEPTNO FROM EMP AS EMP0 GROUP BY EMP0.ENAME, EMP0.SAL, EMP0.DEPTNO HAVING EMP0.SAL > 5000) AS t4 GROUP BY t4.ENAME, t4.SAL, t4.DEPTNO
SELECT * FROM ANON AS t1 WHERE 1 + 2 > 3 + NULL
SELECT 1 FROM (SELECT EMP2.DEPTNO, COUNT(*) FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 7 GROUP BY EMP2.DEPTNO) AS t5 INNER JOIN (SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO > 7) AS t6 ON t5.DEPTNO = t6.DEPTNO INNER JOIN (SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO > 7) AS t7 ON t6.DEPTNO = t7.DEPTNO
SELECT 10 AS MGR FROM EMP AS EMP0 WHERE EMP0.MGR = 10
SELECT EMP0.EMPNO, EMP0.ENAME, EMP0.JOB, EMP0.MGR, EMP0.HIREDATE, EMP0.SAL, EMP0.COMM, EMP0.DEPTNO, EMP0.SLACKER FROM EMP AS EMP0 LEFT JOIN (SELECT DEPT0.DEPTNO, 1 AS i FROM DEPT AS DEPT0) AS t2 ON EMP0.EMPNO = t2.DEPTNO WHERE EMP0.SAL = 4 OR NOT CASE WHEN t2.i IS NOT NULL THEN TRUE ELSE FALSE END
SELECT 1 FROM (SELECT EMP1.COMM AS DEPTNO FROM EMP AS EMP1 WHERE EMP1.DEPTNO > 7) AS t3 INNER JOIN EMP AS EMP2 ON t3.DEPTNO = EMP2.DEPTNO
SELECT EMP1.EMPNO, EMP1.ENAME, EMP1.JOB, EMP1.MGR, EMP1.HIREDATE, EMP1.SAL, EMP1.COMM, EMP1.DEPTNO, EMP1.SLACKER FROM EMP AS EMP1 INNER JOIN (SELECT EMP2.DEPTNO FROM EMP AS EMP2 GROUP BY EMP2.DEPTNO) AS t4 ON EMP1.DEPTNO = t4.DEPTNO
SELECT 1 FROM (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 7) AS t1 INNER JOIN (SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO > 7) AS t2 ON t1.DEPTNO = t2.DEPTNO INNER JOIN (SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO > 7) AS t3 ON t2.DEPTNO = t3.DEPTNO
SELECT t6.ENAME, SUM(count1) FROM (SELECT EMP1.ENAME, COUNT(*) as count1 FROM EMP AS EMP1 GROUP BY EMP1.ENAME UNION ALL SELECT EMP2.ENAME, COUNT(*) as count1 FROM EMP AS EMP2 GROUP BY EMP2.ENAME) AS t6 GROUP BY t6.ENAME
SELECT EMP1.ENAME FROM EMP AS EMP1 INNER JOIN DEPT AS DEPT0 ON EMP1.DEPTNO = DEPT0.DEPTNO INNER JOIN EMP AS EMP2 ON DEPT0.DEPTNO = EMP2.DEPTNO
SELECT T1.K0, T1.C1, T1.F1_A0, T1.F2_A0, T1.F0_C0, T1.F1_C0, T1.F0_C1, T1.F1_C2, T1.F2_C3 FROM T AS T1 INNER JOIN (SELECT T2.F1_C0 AS C0 FROM T AS T2 GROUP BY T2.F1_C0) AS t2 ON T1.F0_C0 = t2.C0
SELECT * FROM (SELECT FALSE AS COL1 UNION ALL SELECT TRUE AS COL1) AS t WHERE NOT COL1
SELECT COUNT(*), t.EXPR$1 FROM (SELECT ENAME, CASE WHEN SAL < 11 THEN 11 ELSE -1 * SAL END AS EXPR$1 FROM EMP) AS t INNER JOIN (SELECT ENAME FROM BONUS) AS t0 ON t.ENAME = t0.ENAME GROUP BY t.EXPR$1
SELECT t1.JOB, t1.MIN_SAL, t1.MIN_DEPTNO, t1.SUM_SAL_2 * t2.$f1 + 1 AS SUM_SAL_PLUS, t1.MAX_SAL, t1.SUM_SAL_2 * t2.$f1 AS SUM_SAL_2, t1.COUNT_SAL * t2.$f1 AS COUNT_SAL, t1.COUNT_MGR * t2.$f1 AS COUNT_MGR FROM (SELECT EMP0.JOB, MIN(EMP0.SAL) AS MIN_SAL, MIN(EMP0.DEPTNO) AS MIN_DEPTNO, SUM(EMP0.SAL) AS SUM_SAL_2, MAX(EMP0.SAL) AS MAX_SAL, COUNT(*) AS COUNT_SAL, COUNT(EMP0.MGR) AS COUNT_MGR FROM EMP AS EMP0 GROUP BY EMP0.JOB) AS t1 INNER JOIN (SELECT DEPT0.NAME, COUNT(*) AS $f1 FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME) AS t2 ON t1.JOB = t2.NAME
SELECT 1 FROM (SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO > 7) AS t1 INNER JOIN (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 7) AS t2 ON t1.DEPTNO = t2.DEPTNO
SELECT t4.ENAME, AVG(t4.EMPNO) FROM (SELECT EMP1.ENAME, EMP1.EMPNO FROM EMP AS EMP1 UNION ALL SELECT EMP2.ENAME, EMP2.EMPNO FROM EMP AS EMP2) AS t4 GROUP BY t4.ENAME
SELECT COUNT(*), t2.expr1 FROM (SELECT EMP0.ENAME, CASE WHEN EMP0.SAL < 11 THEN -1 * EMP0.SAL ELSE EMP0.SAL END AS expr1 FROM EMP AS EMP0) AS t2 FULL JOIN (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY t2.expr1
SELECT 'TABLE' AS U, 't' AS S FROM (VALUES (TRUE)) AS t(EXPR$0)
SELECT 10 AS EMPNO, ENAME, JOB, CAST(NULL AS INTEGER) AS MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS t(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER) WHERE 1 = 0
SELECT NULL AS N FROM EMP AS EMP0
SELECT t10.DEPTNO, SUM(t10.count1) FROM (SELECT EMP1.DEPTNO, COUNT(*) as count1 FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 10 GROUP BY EMP1.DEPTNO UNION ALL SELECT EMP2.DEPTNO, COUNT(*) as count1 FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 20 GROUP BY EMP2.DEPTNO) AS t10 GROUP BY t10.DEPTNO
SELECT EMPNO FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS t(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER) WHERE 1 = 0
SELECT t6.DEPTNO, t6.JOB, SUM(t6.sum1), SUM(t6.count1), MIN(t6.min1), MAX(t6.max1) FROM (SELECT EMP1.DEPTNO, EMP1.JOB, SUM(EMP1.EMPNO) as sum1, COUNT(*) as count1, MIN(EMP1.DEPTNO) as min1, MAX(EMP1.EMPNO) as max1 FROM EMP AS EMP1 GROUP BY EMP1.DEPTNO, EMP1.JOB UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB, SUM(EMP2.EMPNO) as sum1, COUNT(*) as count1, MIN(EMP2.DEPTNO) as min1, MAX(EMP2.EMPNO) as max1 FROM EMP AS EMP2 GROUP BY EMP2.DEPTNO, EMP2.JOB) AS t6 GROUP BY t6.DEPTNO, t6.JOB
SELECT EMP1.ENAME FROM EMP AS EMP1 INNER JOIN DEPT AS DEPT0 ON EMP1.DEPTNO = DEPT0.DEPTNO INNER JOIN EMP AS EMP2 ON EMP1.EMPNO = EMP2.EMPNO INNER JOIN DEPT AS DEPT1 ON EMP1.DEPTNO = DEPT1.DEPTNO INNER JOIN EMP AS EMP3 ON EMP1.EMPNO = EMP3.EMPNO
SELECT 1 FROM EMP AS EMP0, DEPT AS DEPT0 WHERE EMP0.DEPTNO = DEPT0.DEPTNO
SELECT t2.NAME, t1.SUM_SAL, t1.C FROM (SELECT EMP0.JOB, SUM(EMP0.SAL) AS SUM_SAL, COUNT(*) AS C FROM EMP AS EMP0 GROUP BY EMP0.JOB) AS t1 INNER JOIN (SELECT DEPT0.NAME FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME) AS t2 ON t1.JOB = t2.NAME
SELECT 1 FROM EMP AS EMP1 FULL JOIN EMP AS EMP2 ON EMP1.DEPTNO = EMP2.DEPTNO WHERE EMP1.DEPTNO > 7 AND EMP2.DEPTNO > 9
SELECT EMP1.SAL FROM EMP AS EMP1 INNER JOIN DEPT AS DEPT0 ON EMP1.JOB = DEPT0.NAME AND EMP1.EMPNO = DEPT0.DEPTNO INNER JOIN (SELECT EMP2.EMPNO, EMP2.ENAME FROM EMP AS EMP2) AS t5 ON EMP1.ENAME = t5.ENAME AND EMP1.EMPNO = t5.EMPNO
SELECT COUNT(*), t3.expr1 FROM (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t2 LEFT JOIN (SELECT EMP0.ENAME, CASE WHEN EMP0.SAL < 11 THEN -1 * EMP0.SAL ELSE EMP0.SAL END AS expr1 FROM EMP AS EMP0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY t3.expr1
SELECT EMP1.EMPNO FROM EMP AS EMP1, (SELECT 1 AS i FROM EMP AS EMP2 WHERE EMP2.EMPNO < 20 GROUP BY TRUE) AS t4
SELECT EMP0.DEPTNO, MAX(EMP0.MGR) FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO
SELECT t6.ENAME, SUM(t6.sum1), SUM(t6.count1), MIN(t6.min1), MAX(t6.max1) FROM (SELECT EMP1.ENAME, SUM(EMP1.EMPNO) as sum1, COUNT(*) as count1, MIN(EMP1.DEPTNO) as min1, MAX(EMP1.EMPNO) as max1 FROM EMP AS EMP1 GROUP BY EMP1.ENAME UNION ALL SELECT EMP2.ENAME, SUM(EMP2.EMPNO) as sum1, COUNT(*) as count1, MIN(EMP2.DEPTNO) as min1, MAX(EMP2.EMPNO) as max1 FROM EMP AS EMP2 GROUP BY EMP2.ENAME) AS t6 GROUP BY t6.ENAME
SELECT * FROM (SELECT EMP0.ENAME, RANK() OVER (PARTITION BY EMP0.DEPTNO ORDER BY EMP0.SAL RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS R FROM EMP AS EMP0) AS t1 WHERE t1.R < 2
SELECT t6.DEPTNO, t6.JOB, SUM(t6.sum1) FROM (SELECT EMP1.DEPTNO, EMP1.JOB, SUM(EMP1.MGR) as sum1 FROM EMP AS EMP1 GROUP BY EMP1.DEPTNO, EMP1.JOB UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB, SUM(EMP2.MGR) as sum1 FROM EMP AS EMP2 GROUP BY EMP2.DEPTNO, EMP2.JOB) AS t6 GROUP BY t6.DEPTNO, t6.JOB
SELECT DEPT0.NAME FROM DEPT AS DEPT0 WHERE DEPT0.DEPTNO = 10
SELECT DEPTNO, JOB, COUNT(ENAME) FROM (SELECT DEPTNO, JOB, ENAME FROM EMP GROUP BY DEPTNO, JOB, ENAME) AS t0 GROUP BY DEPTNO, JOB
SELECT DEPTNO, JOB, COUNT(ENAME) FILTER (WHERE $g_0), CAST(MIN(EXPR$3) FILTER (WHERE $g_1) AS INTEGER) FROM (SELECT DEPTNO, JOB, ENAME, SUM(SAL) AS EXPR$3, GROUPING(DEPTNO, JOB, ENAME) = 0 AS $g_0, GROUPING(DEPTNO, JOB, ENAME) = 1 AS $g_1 FROM EMP GROUP BY GROUPING SETS((DEPTNO, JOB, ENAME), (DEPTNO, JOB))) AS t1 GROUP BY DEPTNO, JOB
SELECT EMP1.SAL FROM EMP AS EMP1 UNION ALL SELECT EMP2.SAL FROM EMP AS EMP2
SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 EXCEPT SELECT * FROM (SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 EXCEPT SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30) AS t7
SELECT t2.DNAME, COUNT(*) AS C FROM (SELECT DEPT0.NAME AS DNAME FROM DEPT AS DEPT0) AS t2 WHERE t2.DNAME = 'Charlie' GROUP BY t2.DNAME
SELECT COUNT(*), CASE WHEN t2.expr1 THEN 11 ELSE t2.expr2 END FROM (SELECT EMP0.ENAME, EMP0.SAL < 11 AS expr1, -1 * EMP0.SAL AS expr2 FROM EMP AS EMP0) AS t2 FULL JOIN (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY CASE WHEN t2.expr1 THEN 11 ELSE t2.expr2 END
SELECT * FROM (SELECT NULL AS EMPNO, NULL AS ENAME, NULL AS JOB, NULL AS MGR, NULL AS HIREDATE, NULL AS SAL, NULL AS COMM, NULL AS DEPTNO, NULL AS SLACKER, NULL AS DEPTNO0, NULL AS NAME) AS t WHERE 1 = 0
SELECT * FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS t(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER) WHERE 1 = 0
SELECT SAL, SUM(EXPR$1), MIN(EXPR$2), SUM(SAL) FROM (SELECT SAL, SUM(COMM) AS EXPR$1, MIN(COMM) AS EXPR$2 FROM EMP GROUP BY SAL) AS t0 GROUP BY SAL
SELECT EMPNO FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS t(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER) WHERE 1 = 0
SELECT 1 FROM (SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO > 7) AS t1 INNER JOIN (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 7) AS t2 ON t1.DEPTNO = t2.DEPTNO
SELECT t6.DEPTNO, t6.JOB, SUM(t6.count1) FROM (SELECT EMP1.DEPTNO, EMP1.JOB, COUNT(EMP1.MGR) as count1 FROM EMP AS EMP1 GROUP BY EMP1.DEPTNO, EMP1.JOB UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB, COUNT(EMP2.MGR) as count1 FROM EMP AS EMP2 GROUP BY EMP2.DEPTNO, EMP2.JOB) AS t6 GROUP BY t6.DEPTNO, t6.JOB
SELECT COUNT(*), t2.expr1 FROM (SELECT EMP0.ENAME, CASE WHEN EMP0.SAL < 11 THEN -1 * EMP0.SAL ELSE EMP0.SAL END AS expr1 FROM EMP AS EMP0) AS t2 RIGHT JOIN (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY t2.expr1
SELECT COUNT(*), t3.expr1 FROM (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t2 RIGHT JOIN (SELECT EMP0.ENAME, CASE WHEN EMP0.SAL < 11 THEN -1 * EMP0.SAL ELSE EMP0.SAL END AS expr1 FROM EMP AS EMP0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY t3.expr1
SELECT DEPT0.DEPTNO, DEPT0.NAME FROM DEPT AS DEPT0 RIGHT JOIN (SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.SAL > 100 GROUP BY EMP0.DEPTNO) AS t5 ON DEPT0.DEPTNO = t5.DEPTNO
SELECT 1 FROM DEPT AS DEPT0 RIGHT JOIN (SELECT * FROM EMP AS EMP0 WHERE EMP0.SAL > 100) AS t1 ON DEPT0.DEPTNO = t1.DEPTNO
SELECT t5.C1 FROM (SELECT DEPT0.NAME AS C1 FROM DEPT AS DEPT0 WHERE DEPT0.NAME > 'b') AS t5 WHERE t5.C1 > 'c' GROUP BY t5.C1 HAVING COUNT(*) > 30 OR t5.C1 < 'z'
SELECT COALESCE(SUM(t.EXPR$0 * t0.EXPR$0), 0) FROM (SELECT JOB, COUNT(*) AS EXPR$0 FROM EMP GROUP BY JOB) AS t INNER JOIN (SELECT NAME, COUNT(*) AS EXPR$0 FROM DEPT GROUP BY NAME) AS t0 ON t.JOB = t0.NAME
SELECT COUNT(*), t2.expr1 FROM (SELECT EMP0.ENAME, CASE WHEN EMP0.SAL < 11 THEN 11 ELSE -1 * EMP0.SAL END AS expr1 FROM EMP AS EMP0) AS t2 LEFT JOIN (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY t2.expr1
SELECT * FROM ((SELECT NAME FROM DEPT ORDER BY NAME FETCH NEXT 10 ROWS ONLY) UNION ALL (SELECT NAME FROM DEPT ORDER BY NAME FETCH NEXT 10 ROWS ONLY)) AS T1 ORDER BY NAME FETCH NEXT 10 ROWS ONLY
SELECT EMPNO FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS t(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER) WHERE 1 = 0
SELECT t2.ENAME, TRIM( BOTH ' ' FROM t2.JOB ), t2.SAL * 2, t2.DEPTNO FROM ( SELECT EMP0.ENAME, TRIM( BOTH ' ' FROM EMP0.JOB ) AS JOB, EMP0.SAL * 2 AS SAL, EMP0.DEPTNO FROM EMP AS EMP0 INNER JOIN DEPT AS DEPT0 ON EMP0.DEPTNO = DEPT0.DEPTNO ) AS t2 INNER JOIN DEPT AS DEPT1 ON t2.DEPTNO = DEPT1.DEPTNO
SELECT * FROM (SELECT EMP0.ENAME, (RANK() OVER (PARTITION BY EMP0.DEPTNO ORDER BY EMP0.SAL RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) + 1 AS R FROM EMP AS EMP0) AS t1 WHERE t1.R < 2
SELECT 2 FROM (VALUES  (1)) AS t2 LEFT JOIN (VALUES  (1)) AS t3 ON TRUE
SELECT SUM(t1.c) FROM ANON AS t1
SELECT * FROM (SELECT * FROM EMP AS EMP0 ORDER BY EMP0.SAL FETCH NEXT 10 ROWS ONLY) AS t2 LEFT JOIN DEPT AS DEPT0 ON t2.DEPTNO = DEPT0.DEPTNO ORDER BY t2.SAL FETCH NEXT 10 ROWS ONLY
SELECT EMP0.* FROM EMP AS EMP0 RIGHT JOIN (SELECT * FROM DEPT AS DEPT0 ORDER BY DEPT0.NAME) AS t0 ON EMP0.DEPTNO = t0.DEPTNO ORDER BY t0.NAME
SELECT * FROM EMP AS EMP0 LEFT JOIN DEPT AS DEPT0 ON EMP0.DEPTNO = DEPT0.DEPTNO ORDER BY EMP0.SAL, DEPT0.NAME LIMIT 10
SELECT EMP0.* FROM EMP AS EMP0 RIGHT JOIN (SELECT * FROM DEPT AS DEPT0 ORDER BY DEPT0.NAME) AS t0 ON EMP0.DEPTNO = t0.DEPTNO ORDER BY t0.NAME
SELECT * FROM EMP AS EMP0 RIGHT JOIN (SELECT * FROM DEPT AS DEPT0 LIMIT 10) AS t1 ON EMP0.DEPTNO = t1.DEPTNO LIMIT 10
SELECT DEPT3.NAME, DEPT3.DEPTNO FROM DEPT AS DEPT3 UNION ALL SELECT DEPT4.NAME, DEPT4.DEPTNO FROM DEPT AS DEPT4 GROUP BY DEPT4.NAME, DEPT4.DEPTNO UNION ALL SELECT DEPT5.NAME, DEPT5.DEPTNO FROM DEPT AS DEPT5 GROUP BY DEPT5.NAME, DEPT5.DEPTNO UNION ALL SELECT DEPT6.NAME, DEPT6.DEPTNO FROM DEPT AS DEPT6
SELECT * FROM DEPT WHERE EXISTS (SELECT 1 FROM (SELECT DEPTNO FROM EMP WHERE SAL > 100) AS t0 WHERE DEPT.DEPTNO = t0.DEPTNO)
SELECT t.DEPTNO FROM (SELECT DEPTNO FROM DEPT WHERE EXISTS (SELECT 1 FROM (SELECT DEPTNO FROM (SELECT SAL, DEPTNO FROM EMP) AS t0 WHERE SAL > 100) AS t2 WHERE DEPT.DEPTNO = t2.DEPTNO)) AS t INNER JOIN (SELECT ACCTNO FROM ACCOUNT) AS t3 ON t.DEPTNO = t3.ACCTNO
SELECT 1 FROM EMP AS EMP1 INNER JOIN EMP AS EMP2 ON EMP1.DEPTNO = EMP2.DEPTNO
SELECT * FROM (VALUES (NULL, NULL, NULL)) AS t(X, B, A) WHERE 1 = 0
SELECT t1.EMPNO + t1.DEPTNO FROM (SELECT EMP0.EMPNO, EMP0.ENAME, EMP0.SAL, EMP0.COMM, EMP0.DEPTNO FROM EMP AS EMP0) AS t1 WHERE t1.SAL = 10 * t1.COMM AND UPPER(t1.ENAME) = 'FOO'
SELECT DEPTNO, SUM(EXPR$1), MIN(EXPR$2), SUM(SAL) FROM (SELECT DEPTNO, SAL, SUM(COMM) AS EXPR$1, MIN(COMM) AS EXPR$2 FROM EMP GROUP BY DEPTNO, SAL) AS t0 GROUP BY DEPTNO
SELECT EMP0.DEPTNO AS X, SUM(EMP0.SAL), EMP0.EMPNO AS Y FROM EMP AS EMP0 GROUP BY EMP0.EMPNO, EMP0.DEPTNO
SELECT t1.* FROM (SELECT * FROM DEPT AS DEPT0 WHERE DEPT0.DEPTNO <= 10) AS t1 INNER JOIN (SELECT EMP0.DEPTNO FROM EMP AS EMP0) AS t2 ON t1.DEPTNO = t2.DEPTNO
SELECT ENAME, MIN(EXPR$1) FROM (SELECT ENAME, MIN(EMPNO) AS EXPR$1 FROM EMP GROUP BY ENAME UNION ALL SELECT ENAME, MIN(EMPNO) AS EXPR$1 FROM EMP GROUP BY ENAME) AS t3 GROUP BY ENAME
SELECT DEPTNO, JOB, SUM(EXPR$2) FROM (SELECT DEPTNO, JOB, SUM(2) AS EXPR$2 FROM EMP GROUP BY DEPTNO, JOB UNION ALL SELECT DEPTNO, JOB, SUM(3) AS EXPR$2 FROM EMP GROUP BY DEPTNO, JOB) AS t3 GROUP BY DEPTNO, JOB
SELECT DEPT0.DEPTNO, DEPT0.NAME, COUNT(*) AS C FROM DEPT AS DEPT0 GROUP BY DEPT0.DEPTNO, DEPT0.NAME HAVING DEPT0.NAME = 'Charlie'
SELECT t2.DNAME, t2.DDEPTNO, COUNT(*) AS C FROM (SELECT DEPT0.NAME AS DNAME, DEPT0.DEPTNO AS DDEPTNO FROM DEPT AS DEPT0) AS t2 WHERE t2.DNAME = 'Charlie' GROUP BY t2.DNAME, t2.DDEPTNO
SELECT 1 FROM (SELECT * FROM (SELECT EMP3.DEPTNO FROM EMP AS EMP3 WHERE EMP3.DEPTNO > 7 UNION ALL SELECT EMP4.DEPTNO FROM EMP AS EMP4 WHERE EMP4.DEPTNO > 10) AS t12 UNION ALL SELECT EMP5.DEPTNO FROM EMP AS EMP5 WHERE EMP5.DEPTNO > 1) AS t15 INNER JOIN (SELECT * FROM EMP AS EMP6 WHERE EMP6.DEPTNO > 7 OR EMP6.DEPTNO > 10 OR EMP6.DEPTNO > 1) AS t16 ON t15.DEPTNO = t16.DEPTNO
SELECT DEPT0.NAME, POWER((SUM(DEPT0.DEPTNO * DEPT0.DEPTNO) - SUM(DEPT0.DEPTNO) * SUM(DEPT0.DEPTNO) / COUNT(*)) / COUNT(*), 0.5), SUM(DEPT0.DEPTNO) / COUNT(*), POWER((SUM(DEPT0.DEPTNO * DEPT0.DEPTNO) - SUM(DEPT0.DEPTNO) * SUM(DEPT0.DEPTNO) / COUNT(*)) / CASE WHEN COUNT(*) = 1 THEN NULL ELSE COUNT(*) - 1 END, 0.5), (SUM(DEPT0.DEPTNO * DEPT0.DEPTNO) - SUM(DEPT0.DEPTNO) * SUM(DEPT0.DEPTNO) / COUNT(*)) / COUNT(*), (SUM(DEPT0.DEPTNO * DEPT0.DEPTNO) - SUM(DEPT0.DEPTNO) * SUM(DEPT0.DEPTNO) / COUNT(*)) / CASE WHEN COUNT(*) = 1 THEN NULL ELSE COUNT(*) - 1 END FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME
SELECT EMP0.DEPTNO, MAX(EMP0.MGR) FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO
SELECT t8.EMPNO, t8.ENAME, t8.JOB, t8.MGR, t8.HIREDATE, t8.SAL, t8.COMM, t8.DEPTNO, t8.SLACKER FROM (SELECT EMP2.EMPNO, EMP2.ENAME, EMP2.JOB, EMP2.MGR, EMP2.HIREDATE, EMP2.SAL, EMP2.COMM, EMP2.DEPTNO, EMP2.SLACKER, COUNT(*) AS $f9 FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 GROUP BY EMP2.EMPNO, EMP2.ENAME, EMP2.JOB, EMP2.MGR, EMP2.HIREDATE, EMP2.SAL, EMP2.COMM, EMP2.DEPTNO, EMP2.SLACKER UNION ALL SELECT EMP3.EMPNO, EMP3.ENAME, EMP3.JOB, EMP3.MGR, EMP3.HIREDATE, EMP3.SAL, EMP3.COMM, EMP3.DEPTNO, EMP3.SLACKER, COUNT(*) AS $f9 FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 GROUP BY EMP3.EMPNO, EMP3.ENAME, EMP3.JOB, EMP3.MGR, EMP3.HIREDATE, EMP3.SAL, EMP3.COMM, EMP3.DEPTNO, EMP3.SLACKER) AS t8 GROUP BY t8.EMPNO, t8.ENAME, t8.JOB, t8.MGR, t8.HIREDATE, t8.SAL, t8.COMM, t8.DEPTNO, t8.SLACKER HAVING COUNT(*) = 2 INTERSECT ALL SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30
SELECT CAST(NULL AS INTEGER) AS EMPNO, CAST(NULL AS VARCHAR(20)) AS ENAME, CAST(NULL AS VARCHAR(10)) AS JOB, CAST(NULL AS INTEGER) AS MGR, CAST(NULL AS TIMESTAMP(0)) AS HIREDATE, CAST(NULL AS INTEGER) AS SAL, CAST(NULL AS INTEGER) AS COMM, CAST(NULL AS INTEGER) AS DEPTNO, CAST(NULL AS BOOLEAN) AS SLACKER, DEPTNO AS DEPTNO0, NAME FROM DEPT
SELECT 1 FROM (SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO > 7) AS t2 LEFT JOIN (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 7) AS t3 ON t2.DEPTNO = t3.DEPTNO WHERE t3.DEPTNO > 9
SELECT t6.DEPTNO, t6.JOB, MAX(max1) FROM (SELECT EMP1.DEPTNO, EMP1.JOB, MAX(EMP1.MGR) as max1 FROM EMP AS EMP1 GROUP BY EMP1.DEPTNO, EMP1.JOB UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB, MAX(EMP2.MGR) as max1 FROM EMP AS EMP2 GROUP BY EMP2.DEPTNO, EMP2.JOB) AS t6 GROUP BY t6.DEPTNO, t6.JOB
SELECT FALSE FROM (VALUES  (0)) AS t2
SELECT SAL FROM (SELECT * FROM EMP, (SELECT EMPNO AS EMPNO2, ENAME AS ENAME2, JOB AS JOB2, MGR AS MGR2, HIREDATE AS HIREDATE2, SAL AS SAL2, COMM AS COMM2, DEPTNO AS DEPTNO2, SLACKER AS SLACKER2 FROM EMP) AS t UNION ALL SELECT * FROM EMP AS EMP1, (SELECT * FROM EMP) AS t0) AS t1
SELECT 1 FROM (SELECT * FROM DEPT AS DEPT0 WHERE DEPT0.NAME = 'Charlie') AS t1 INNER JOIN (SELECT * FROM EMP AS EMP0 WHERE EMP0.SAL > 100) AS t2 ON t1.DEPTNO = t2.DEPTNO
SELECT t4.DEPTNO, t4.JOB, AVG(t4.EMPNO) FROM (SELECT EMP1.DEPTNO, EMP1.JOB, EMP1.EMPNO FROM EMP AS EMP1 UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB, EMP2.EMPNO FROM EMP AS EMP2) AS t4 GROUP BY t4.DEPTNO, t4.JOB
SELECT EMP0.SAL FROM EMP AS EMP0 WHERE EMP0.SAL = 1000 OR EMP0.SAL = 2000
SELECT DEPT0.NAME, MAX(DEPT0.NAME), SUM(DEPT0.DEPTNO) / COUNT(*), MIN(DEPT0.NAME) FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME
SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 UNION ALL SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 UNION ALL SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30
SELECT t6.NAME, t6.EMPNO FROM (SELECT t4.DEPTNO, t4.NAME, t5.EMPNO, t5.ENAME, t5.JOB, t5.MGR, t5.HIREDATE, t5.SAL, t5.COMM, t5.DEPTNO AS DEPTNO1, t5.SLACKER FROM (SELECT DEPT0.DEPTNO, DEPT0.NAME, DEPT0.DEPTNO AS DEPTNO0 FROM DEPT AS DEPT0) AS t4 INNER JOIN (SELECT EMP0.EMPNO, EMP0.ENAME, EMP0.JOB, EMP0.MGR, EMP0.HIREDATE, EMP0.SAL, EMP0.COMM, EMP0.DEPTNO, EMP0.SLACKER, EMP0.DEPTNO AS DEPTNO0 FROM EMP AS EMP0) AS t5 ON t4.DEPTNO0 = t5.DEPTNO0) AS t6 WHERE t6.JOB = 'Manager'
SELECT 1 FROM DEPT AS DEPT0 INNER JOIN (SELECT * FROM EMP AS EMP0 WHERE EMP0.SAL > 100) AS t1 ON DEPT0.DEPTNO = t1.DEPTNO
SELECT SUM(t6.sum1) FROM (SELECT SUM(EMP1.MGR) as sum1 FROM EMP AS EMP1 UNION ALL SELECT SUM(EMP2.MGR) as sum2 FROM EMP AS EMP2) AS t6
SELECT * FROM (VALUES  (30, 3)) AS t8 EXCEPT SELECT * FROM (VALUES  (40, 4)) AS t9
SELECT * FROM (SELECT EMP0.JOB FROM EMP AS EMP0 WHERE EMP0.EMPNO = 10 GROUP BY EMP0.JOB) AS t2 INNER JOIN (SELECT DEPT0.NAME FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME) AS t3 ON t2.JOB = t3.NAME
SELECT t5.JOB, t7.NAME FROM (SELECT EMP0.JOB, EMP0.DEPTNO + EMP0.EMPNO AS $f9 FROM EMP AS EMP0 WHERE EMP0.EMPNO = 10 GROUP BY EMP0.JOB, EMP0.DEPTNO + EMP0.EMPNO) AS t5 INNER JOIN (SELECT DEPT0.NAME, DEPT0.DEPTNO + 5 AS $f2 FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME, DEPT0.DEPTNO + 5) AS t7 ON t5.JOB = t7.NAME AND t5.$f9 = t7.$f2 GROUP BY t5.JOB, t7.NAME
SELECT t1.EMPNO, DEPT0.DEPTNO AS DEPTNO0 FROM (SELECT * FROM EMP AS EMP0 WHERE EMP0.EMPNO = 10) AS t1 INNER JOIN DEPT AS DEPT0 ON t1.EMPNO = DEPT0.DEPTNO GROUP BY t1.EMPNO, DEPT0.DEPTNO
SELECT t0.DEPTNO FROM (SELECT EMP0.DEPTNO FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO) AS t0 INNER JOIN DEPT AS DEPT0 ON t0.DEPTNO = DEPT0.DEPTNO
SELECT t0.DEPTNO, DEPT0.DEPTNO AS DEPTNO0 FROM (SELECT EMP0.DEPTNO FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO) AS t0 INNER JOIN DEPT AS DEPT0 ON t0.DEPTNO = DEPT0.DEPTNO
SELECT 3, 22, 26, CAST(NULL AS INTEGER), CAST(2 AS INTEGER), ROW(15) FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS t(DEPTNO, NAME, EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO0, SLACKER) WHERE 1 = 0
SELECT t8.ENAME, SUM(t8.sum1) FROM (SELECT EMP1.ENAME, SUM(NULL) as sum1 FROM EMP AS EMP1 GROUP BY EMP1.ENAME UNION ALL SELECT EMP2.ENAME, SUM(NULL) FROM EMP AS EMP2 GROUP BY EMP2.ENAME) AS t8 GROUP BY t8.ENAME
SELECT EMP0.ENAME FROM EMP AS EMP0 INNER JOIN (SELECT * FROM DEPT AS DEPT0 WHERE DEPT0.DEPTNO = 10) AS t1 ON EMP0.DEPTNO = t1.DEPTNO
SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 UNION SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 UNION SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30
SELECT DEPT0.DEPTNO, DEPT0.NAME, t0.EMPNO AS EMPNO, t0.ENAME AS ENAME, t0.JOB AS JOB, t0.MGR, t0.HIREDATE AS HIREDATE, t0.SAL AS SAL, t0.COMM AS COMM, t0.DEPTNO AS DEPTNO0, t0.SLACKER AS SLACKER FROM DEPT AS DEPT0 INNER JOIN (SELECT * FROM EMP AS EMP0 WHERE EMP0.SAL > 100) AS t0 ON DEPT0.DEPTNO = t0.DEPTNO
SELECT t1.JOB, CAST(t1.SAL * t2.$f1 AS INTEGER) FROM (SELECT JOB, SAL FROM EMP WHERE EMPNO = 10) AS t1 INNER JOIN (SELECT NAME, COUNT(*) AS $f1 FROM DEPT GROUP BY NAME) AS t2 ON t1.JOB = t2.NAME
SELECT EMP.EMPNO FROM EMP LEFT JOIN (SELECT DEPTNO, TRUE AS i FROM EMP WHERE EMPNO < 20 GROUP BY DEPTNO, TRUE) AS t1 ON EMP.DEPTNO = t1.DEPTNO WHERE t1.i IS NOT NULL OR EMP.SAL < 100
SELECT COUNT(*) FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 10
SELECT 1 FROM (SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 7 OR EMP1.DEPTNO = 9 OR EMP1.COMM > 10) AS t1 INNER JOIN EMP AS EMP2 ON t1.DEPTNO = EMP2.DEPTNO
SELECT * FROM (VALUES (NULL)) AS t(EXPR$0) WHERE 1 = 0
SELECT 1 FROM (SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO = 7 OR EMP1.DEPTNO = 9 OR EMP1.DEPTNO > 10) AS t1 INNER JOIN (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 7 OR EMP2.DEPTNO = 9 OR EMP2.DEPTNO > 10) AS t2 ON t1.DEPTNO = t2.DEPTNO
SELECT EMP0.DEPTNO, MAX(EMP0.ENAME) FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO
SELECT t0.DEPTNO, t0.NAME FROM (SELECT * FROM DEPT AS DEPT1 UNION ALL SELECT * FROM DEPT AS DEPT2) AS t0 GROUP BY t0.DEPTNO, t0.NAME
SELECT t1.ENAME FROM (SELECT EMP0.DEPTNO,EMP0.ENAME FROM EMP AS EMP0 INNER JOIN DEPT AS DEPT0 ON EMP0.DEPTNO = DEPT0.DEPTNO WHERE EMP0.ENAME = 'foo') AS t1 INNER JOIN DEPT AS DEPT1 ON t1.DEPTNO = DEPT1.DEPTNO
SELECT t7.DEPTNO, t7.JOB FROM (SELECT EMP1.DEPTNO, EMP1.JOB FROM EMP AS EMP1 UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB FROM EMP AS EMP2) AS t7 GROUP BY t7.DEPTNO, t7.JOB
SELECT * FROM (SELECT * FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 10) AS t1 WHERE 15 > t1.EMPNO
SELECT t6.ENAME, SUM(sum1) FROM (SELECT EMP1.ENAME, SUM(EMP1.MGR) as sum1 FROM EMP AS EMP1 GROUP BY EMP1.ENAME UNION ALL SELECT EMP2.ENAME, SUM(EMP2.MGR) FROM EMP AS EMP2 GROUP BY EMP2.ENAME) AS t6 GROUP BY t6.ENAME
SELECT * FROM (VALUES (NULL)) AS t(EXPR$0) WHERE 1 = 0
SELECT 1 FROM (SELECT EMP1.COMM AS DEPTNO FROM EMP AS EMP1 WHERE EMP1.COMM > 7) AS t3 INNER JOIN (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 7) AS t4 ON t3.DEPTNO = t4.DEPTNO
SELECT 1 FROM (SELECT EMP1.DEPTNO, COUNT(*) FROM EMP AS EMP1 WHERE EMP1.DEPTNO > 7 GROUP BY EMP1.DEPTNO) AS t5 INNER JOIN (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 7) AS t6 ON t5.DEPTNO = t6.DEPTNO
SELECT * FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS t(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER) WHERE 1 = 0
SELECT t3.NAME, SUM(t3.CN), SUM(t3.SM) FROM (SELECT DEPT0.NAME, COUNT(*) AS CN, SUM(DEPT0.DEPTNO) AS SM FROM DEPT AS DEPT0 GROUP BY DEPT0.NAME) AS t3 GROUP BY t3.NAME
SELECT DEPTNO, COUNT(ENAME) FROM (SELECT ENAME, DEPTNO FROM EMP GROUP BY ENAME, DEPTNO) AS t GROUP BY DEPTNO
SELECT DEPTNO, COUNT(ENAME) FILTER (WHERE $g_0), CAST(MIN(EXPR$2) FILTER (WHERE $g_1) AS INTEGER) FROM (SELECT DEPTNO, ENAME, SUM(SAL) AS EXPR$2, GROUPING(DEPTNO, ENAME) = 0 AS $g_0, GROUPING(DEPTNO, ENAME) = 1 AS $g_1 FROM EMP GROUP BY GROUPING SETS((ENAME, DEPTNO), DEPTNO)) AS t1 GROUP BY DEPTNO
SELECT COUNT(DEPTNO) FILTER (WHERE $g_0), CAST(MIN(EXPR$1) FILTER (WHERE $g_0) AS INTEGER) FROM (SELECT DEPTNO, SUM(SAL) AS EXPR$1, GROUPING(DEPTNO) = 0 AS $g_0 FROM EMP GROUP BY DEPTNO) AS t1 GROUP BY DEPTNO
SELECT EMP1.EMPNO, CASE WHEN t5.i IS NOT NULL THEN TRUE ELSE FALSE END AS D FROM EMP AS EMP1 LEFT JOIN (SELECT EMP2.DEPTNO, 1 AS i FROM EMP AS EMP2 WHERE EMP2.EMPNO < 20 GROUP BY EMP2.DEPTNO, TRUE) AS t5 ON EMP1.DEPTNO = t5.DEPTNO
SELECT EMP0.DEPTNO, EMP0.ENAME, NULL FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO, EMP0.ENAME, NULL
SELECT t6.DEPTNO, t6.JOB, SUM(count1) FROM (SELECT EMP1.DEPTNO, EMP1.JOB, COUNT(*) as count1 FROM EMP AS EMP1 GROUP BY EMP1.DEPTNO, EMP1.JOB UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB, COUNT(*) as count1 FROM EMP AS EMP2 GROUP BY EMP2.DEPTNO, EMP2.JOB) AS t6 GROUP BY t6.DEPTNO, t6.JOB
SELECT t0.EMPNO, COALESCE(SUM(t0.EXPR$1), 0), AVG(t0.DEPTNO0) FROM (SELECT EMP.EMPNO, DEPT.DEPTNO AS DEPTNO0, COUNT(*) AS EXPR$1 FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO GROUP BY EMP.EMPNO, DEPT.DEPTNO) AS t0 GROUP BY t0.EMPNO
SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 UNION SELECT * FROM (SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 INTERSECT SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30) AS t7
SELECT DEPTNO, SUM(EXPR$1), SUM(SAL), MAX(EXPR$3), MAX(EXPR$4) FROM (SELECT DEPTNO, SAL, SUM(DEPTNO) AS EXPR$1, MAX(DEPTNO) AS EXPR$3, MAX(COMM) AS EXPR$4 FROM EMP GROUP BY DEPTNO, SAL) AS t0 GROUP BY DEPTNO
SELECT DEPTNO, COALESCE(SUM(EXPR$1), 0), SUM(SAL) FROM (SELECT DEPTNO, SAL, COUNT(*) AS EXPR$1 FROM EMP GROUP BY DEPTNO, SAL) AS t0 GROUP BY DEPTNO
SELECT EMP0.EMPNO FROM EMP AS EMP0 WHERE EMP0.EMPNO = 10
SELECT t6.DEPTNO, t6.JOB, MIN(t6.min1) FROM (SELECT EMP1.DEPTNO, EMP1.JOB, MIN(EMP1.EMPNO) as min1 FROM EMP AS EMP1 GROUP BY EMP1.DEPTNO, EMP1.JOB UNION ALL SELECT EMP2.DEPTNO, EMP2.JOB, MIN(EMP2.EMPNO) as min1 FROM EMP AS EMP2 GROUP BY EMP2.DEPTNO, EMP2.JOB) AS t6 GROUP BY t6.DEPTNO, t6.JOB
SELECT 4, 2 + 3, MAX(EMP0.MGR) FROM EMP AS EMP0 GROUP BY 4
SELECT EMP0.DEPTNO, MAX(EMP0.MGR) FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO, EMP0.DEPTNO + 42
SELECT * FROM (SELECT NULL AS EXPR$0, NULL AS EXPR$1) AS t WHERE 1 = 0
SELECT COUNT(*), t3.expr1 FROM (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t2 RIGHT JOIN (SELECT EMP0.ENAME, CASE WHEN EMP0.SAL < 11 THEN 11 ELSE -1 * EMP0.SAL END AS expr1 FROM EMP AS EMP0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY t3.expr1
SELECT 10 AS DEPTNO, 11, EMP0.EMPNO + 10 FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 10
SELECT * FROM (SELECT EMP2.DEPTNO FROM EMP AS EMP2 WHERE EMP2.DEPTNO < 4) AS t6 INNER JOIN (SELECT * FROM (SELECT EMP3.DEPTNO FROM EMP AS EMP3 WHERE EMP3.DEPTNO > 7 UNION ALL SELECT EMP4.DEPTNO FROM EMP AS EMP4) AS t10 WHERE t10.DEPTNO < 4) AS t11 ON t6.DEPTNO = t11.DEPTNO
SELECT * FROM EMP AS EMP1 WHERE (EMP1.EMPNO, EMP1.DEPTNO) IN (SELECT EMP2.EMPNO, EMP2.DEPTNO FROM EMP AS EMP2 GROUP BY EMP2.EMPNO, EMP2.DEPTNO) OR EMP1.DEPTNO < 100
SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 INTERSECT SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 INTERSECT SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30
SELECT ENAME, SUM(EXPR$1) FROM (SELECT ENAME, SUM(2) AS EXPR$1 FROM EMP GROUP BY ENAME UNION ALL SELECT ENAME, SUM(3) AS EXPR$1 FROM EMP GROUP BY ENAME) AS t3 GROUP BY ENAME
SELECT 1 FROM EMP AS EMP0 INNER JOIN DEPT AS DEPT0 ON EMP0.DEPTNO = DEPT0.DEPTNO INNER JOIN DEPT AS DEPT1 ON EMP0.DEPTNO = DEPT1.DEPTNO
SELECT EMP1.EMPNO, CASE WHEN t3.i IS NOT NULL THEN TRUE ELSE FALSE END AS D FROM EMP AS EMP1 LEFT JOIN (SELECT 1 AS i FROM EMP AS EMP2 WHERE EMP2.EMPNO < 20 GROUP BY TRUE) AS t3 ON TRUE
SELECT t1.ENAME FROM (SELECT * FROM EMP AS EMP0 WHERE EMP0.ENAME = 'foo') AS t1 INNER JOIN DEPT AS DEPT0 ON t1.DEPTNO = DEPT0.DEPTNO
SELECT 1 FROM (SELECT * FROM DEPT AS DEPT0 WHERE DEPT0.NAME = 'Charlie') AS t1 INNER JOIN EMP AS EMP0 ON t1.DEPTNO = EMP0.DEPTNO
SELECT DEPTNO, COUNT(DEPTNO, JOB) FILTER (WHERE $g_0) AS CDDJ, CAST(MIN(S) FILTER (WHERE $g_1) AS INTEGER) AS S FROM (SELECT DEPTNO, JOB, SUM(SAL) AS S, GROUPING(DEPTNO, JOB) = 0 AS $g_0, GROUPING(DEPTNO, JOB) = 1 AS $g_1 FROM EMP GROUP BY GROUPING SETS((DEPTNO, JOB), DEPTNO)) AS t1 GROUP BY DEPTNO
SELECT t1.DEPTNO, t2.DEPTNO AS DEPTNO0 FROM (SELECT DEPT0.DEPTNO, DEPT0.NAME, DEPT0.DEPTNO + 10 AS $f2 FROM DEPT AS DEPT0) AS t1 INNER JOIN (SELECT EMP0.EMPNO, EMP0.ENAME, EMP0.JOB, EMP0.MGR, EMP0.HIREDATE, EMP0.SAL, EMP0.COMM, EMP0.DEPTNO, EMP0.SLACKER, EMP0.DEPTNO * 2 AS $f9 FROM EMP AS EMP0) AS t2 ON t1.$f2 = t2.$f9
SELECT EMP1.ENAME FROM EMP AS EMP1 INNER JOIN (SELECT * FROM DEPT AS DEPT0 WHERE DEPT0.NAME = 'foo') AS t1 ON EMP1.DEPTNO = t1.DEPTNO INNER JOIN EMP AS EMP2 ON t1.DEPTNO = EMP2.DEPTNO
SELECT 1 FROM (SELECT * FROM DEPT AS DEPT0 WHERE DEPT0.NAME = 'Charlie') AS t1 LEFT JOIN EMP AS EMP0 ON t1.DEPTNO = EMP0.DEPTNO
SELECT EMP0.DEPTNO, MAX(EMP0.MGR) FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO
SELECT 1 FROM (SELECT EMP2.DEPTNO FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 7 UNION ALL SELECT EMP3.DEPTNO FROM EMP AS EMP3 WHERE EMP3.DEPTNO > 10) AS t9 INNER JOIN (SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO > 7 OR EMP4.DEPTNO > 10) AS t10 ON t9.DEPTNO = t10.DEPTNO
SELECT * FROM (SELECT * FROM EMP AS EMP0 WHERE EMP0.EMPNO = 10) AS t0 LEFT JOIN (SELECT * FROM DEPT AS DEPT0 WHERE DEPT0.DEPTNO = 10) AS t1 ON TRUE
SELECT COUNT(*) FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 10
SELECT COUNT(*) FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 30 OR EMP0.DEPTNO = 10
SELECT EMP2.EMPNO FROM EMP AS EMP2 LEFT JOIN (DEPT AS DEPT0 LEFT JOIN (SELECT SINGLE_VALUE(EMP3.DEPTNO) AS $f0 FROM EMP AS EMP3 WHERE EMP3.EMPNO < 20) AS t6 ON TRUE LEFT JOIN (SELECT SINGLE_VALUE(EMP4.DEPTNO) AS $f0 FROM EMP AS EMP4 WHERE EMP4.EMPNO > 100) AS t9 ON TRUE) ON t6.$f0 < t9.$f0
SELECT 4, 2 + 3, MAX(5) FROM EMP AS EMP0 GROUP BY 4
SELECT 1 FROM EMP AS EMP0 RIGHT JOIN DEPT AS DEPT0 ON EMP0.DEPTNO = DEPT0.DEPTNO
SELECT SAL2 AS SAL FROM (SELECT * FROM (SELECT EMPNO AS EMPNO2, ENAME AS ENAME2, JOB AS JOB2, MGR AS MGR2, HIREDATE AS HIREDATE2, SAL AS SAL2, COMM AS COMM2, DEPTNO AS DEPTNO2, SLACKER AS SLACKER2 FROM EMP) AS t, EMP AS EMP0 UNION ALL SELECT * FROM (SELECT * FROM EMP) AS t0, EMP AS EMP2) AS t1
SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 UNION SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20 UNION SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30
SELECT EMP0.DEPTNO FROM EMP AS EMP0 GROUP BY EMP0.DEPTNO HAVING COUNT(*) > 1
SELECT * FROM (SELECT NULL AS EXPR$0, NULL AS EXPR$1) AS t WHERE 1 = 0
SELECT EMP1.EMPNO FROM EMP AS EMP1 LEFT JOIN (SELECT 1 AS i FROM EMP AS EMP2 WHERE EMP2.EMPNO < 20 GROUP BY TRUE) AS t4 ON TRUE WHERE t4.i IS NOT NULL OR EMP1.SAL < 100
SELECT EMP0.JOB, 10 AS EMPNO, EMP0.SAL, SUM(EMP0.SAL) AS S FROM EMP AS EMP0 WHERE EMP0.EMPNO = 10 GROUP BY EMP0.JOB, EMP0.SAL
SELECT * FROM (SELECT EMP0.MGR FROM EMP AS EMP0) AS t2 WHERE t2.MGR < 10
SELECT t6.SAL FROM (SELECT * FROM (SELECT EMP1.SAL, EMP1.DEPTNO FROM EMP AS EMP1) AS t5 WHERE t5.DEPTNO = 200) AS t6 INNER JOIN (SELECT t7.DEPTNO FROM (SELECT EMP2.SAL, EMP2.DEPTNO FROM EMP AS EMP2) AS t7 WHERE t7.SAL = 100) AS t9 ON t6.DEPTNO = t9.DEPTNO
SELECT EMP1.EMPNO, t4.$f0 AS D FROM EMP AS EMP1 LEFT JOIN (SELECT SINGLE_VALUE(EMP2.DEPTNO) AS $f0 FROM EMP AS EMP2 WHERE EMP2.EMPNO < 20) AS t4 ON TRUE
SELECT COUNT(ENAME) FILTER (WHERE $g_1), COUNT(JOB) FILTER (WHERE $g_2) FROM (SELECT ENAME, JOB, GROUPING(ENAME, JOB) = 1 AS $g_1, GROUPING(ENAME, JOB) = 2 AS $g_2 FROM EMP GROUP BY GROUPING SETS(ENAME, JOB)) AS t0
SELECT EMP.EMPNO, CASE WHEN t2.c = 0 THEN FALSE WHEN CASE WHEN TRUE THEN CAST(EMP.DEPTNO AS INTEGER) ELSE NULL END IS NULL THEN NULL WHEN t6.i IS NOT NULL THEN TRUE WHEN t2.ck < t2.c THEN NULL ELSE FALSE END AS D FROM EMP CROSS JOIN (SELECT COUNT(*) AS c, COUNT(DEPTNO) AS ck FROM (SELECT EMPNO, CASE WHEN TRUE THEN CAST(DEPTNO AS INTEGER) ELSE NULL END AS DEPTNO FROM EMP) AS t WHERE EMPNO < 20) AS t2 LEFT JOIN (SELECT DEPTNO, TRUE AS i FROM (SELECT EMPNO, CASE WHEN TRUE THEN CAST(DEPTNO AS INTEGER) ELSE NULL END AS DEPTNO FROM EMP) AS t3 WHERE EMPNO < 20 GROUP BY DEPTNO, TRUE) AS t6 ON CASE WHEN TRUE THEN CAST(EMP.DEPTNO AS INTEGER) ELSE NULL END = t6.DEPTNO
SELECT EMP0.ENAME, EMP0.SAL, EMP0.DEPTNO FROM EMP AS EMP0 GROUP BY EMP0.ENAME, EMP0.SAL, EMP0.DEPTNO HAVING EMP0.SAL > 5000
SELECT COUNT(*) AS C FROM EMP AS EMP0 WHERE EMP0.DEPTNO = 10 GROUP BY EMP0.DEPTNO
SELECT t7.JOB FROM (SELECT EMP0.SAL, 'Clerk' AS JOB, COUNT(*) AS $f2 FROM EMP AS EMP0 WHERE EMP0.SAL IS NULL AND EMP0.JOB = 'Clerk' GROUP BY EMP0.SAL) AS t7 WHERE t7.$f2 > 3
SELECT 10 AS EMPNO, t5.ENAME, t5.JOB, t5.MGR, t5.HIREDATE, t5.SAL, t5.COMM, t5.DEPTNO, t5.SLACKER, 10 AS DEPTNO0, t7.NAME FROM (SELECT 10 AS EMPNO, EMP0.ENAME, EMP0.JOB, EMP0.MGR, EMP0.HIREDATE, EMP0.SAL, EMP0.COMM, EMP0.DEPTNO, EMP0.SLACKER, EMP0.DEPTNO + 10 AS $f9 FROM EMP AS EMP0 WHERE EMP0.EMPNO = 10) AS t5 INNER JOIN (SELECT 10 AS DEPTNO, DEPT0.NAME, 15 AS $f2 FROM DEPT AS DEPT0 WHERE DEPT0.DEPTNO = 10) AS t7 ON t5.$f9 = 15
SELECT COUNT(*), t.EXPR$1 FROM (SELECT ENAME, CASE WHEN SAL < 11 THEN -1 * SAL ELSE SAL END AS EXPR$1 FROM EMP) AS t INNER JOIN (SELECT ENAME FROM BONUS) AS t0 ON t.ENAME = t0.ENAME GROUP BY t.EXPR$1
SELECT COUNT(*), CASE WHEN t3.expr1 THEN 11 ELSE t3.expr2 END FROM (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t2 LEFT JOIN (SELECT EMP0.ENAME, EMP0.SAL < 11 AS expr1, -1 * EMP0.SAL AS expr2 FROM EMP AS EMP0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY CASE WHEN t3.expr1 THEN 11 ELSE t3.expr2 END
SELECT DEPT0.DEPTNO, DEPT0.NAME FROM DEPT AS DEPT0 FULL JOIN (SELECT EMP0.DEPTNO FROM EMP AS EMP0 WHERE EMP0.SAL > 100 GROUP BY EMP0.DEPTNO) AS t5 ON DEPT0.DEPTNO = t5.DEPTNO
SELECT DEPT0.NAME FROM DEPT AS DEPT0
SELECT EMP1.EMPNO, CASE WHEN t4.i IS NOT NULL THEN TRUE ELSE FALSE END AS D FROM EMP AS EMP1 LEFT JOIN (SELECT EMP2.EMPNO, EMP2.DEPTNO, 1 AS i FROM EMP AS EMP2 WHERE EMP2.EMPNO < 20) AS t4 ON EMP1.EMPNO = t4.EMPNO AND EMP1.DEPTNO = t4.DEPTNO
SELECT * FROM (SELECT NULL AS EMPNO, NULL AS ENAME, NULL AS JOB, NULL AS MGR, NULL AS HIREDATE, NULL AS SAL, NULL AS COMM, NULL AS DEPTNO, NULL AS SLACKER, NULL AS DEPTNO0, NULL AS NAME) AS t WHERE 1 = 0
SELECT EMP0.SAL FROM EMP AS EMP0 WHERE CASE WHEN EMP0.SAL = 1000 THEN EMP0.SAL = 1000 ELSE EMP0.SAL = 2000 END
SELECT 1 FROM (SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO > 9) AS t2 RIGHT JOIN (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO > 9) AS t3 ON t2.DEPTNO = t3.DEPTNO WHERE t2.DEPTNO > 7
SELECT DEPTNO, COUNT(ENAME) FILTER (WHERE $g_1) AS CDE, COUNT(JOB, ENAME) FILTER (WHERE $g_0) AS CDJE, COUNT(DEPTNO, JOB) FILTER (WHERE $g_2) AS CDDJ, CAST(MIN(S) FILTER (WHERE $g_3) AS INTEGER) AS S FROM (SELECT DEPTNO, ENAME, JOB, SUM(SAL) AS S, GROUPING(DEPTNO, ENAME, JOB) = 0 AS $g_0, GROUPING(DEPTNO, ENAME, JOB) = 1 AS $g_1, GROUPING(DEPTNO, ENAME, JOB) = 2 AS $g_2, GROUPING(DEPTNO, ENAME, JOB) = 3 AS $g_3 FROM EMP GROUP BY GROUPING SETS((ENAME, JOB, DEPTNO), (ENAME, DEPTNO), (JOB, DEPTNO), DEPTNO)) AS t0 GROUP BY DEPTNO
SELECT DEPTNO, JOB, SUM(EXPR$2) FROM (SELECT DEPTNO, JOB, SUM(CAST(NULL AS INTEGER)) AS EXPR$2 FROM EMP GROUP BY DEPTNO, JOB UNION ALL SELECT DEPTNO, JOB, SUM(CAST(NULL AS INTEGER)) AS EXPR$2 FROM EMP GROUP BY DEPTNO, JOB) AS t3 GROUP BY ROLLUP(DEPTNO, JOB)
SELECT EMP.EMPNO FROM EMP CROSS JOIN (SELECT COUNT(*) AS c, COUNT(CASE WHEN TRUE THEN CAST(DEPTNO AS INTEGER) ELSE NULL END) AS ck FROM EMP WHERE EMPNO < 20) AS t1 LEFT JOIN (SELECT CASE WHEN TRUE THEN CAST(DEPTNO AS INTEGER) ELSE NULL END AS EXPR$0, TRUE AS i FROM EMP WHERE EMPNO < 20 GROUP BY CASE WHEN TRUE THEN CAST(DEPTNO AS INTEGER) ELSE NULL END, TRUE) AS t4 ON EMP.DEPTNO = t4.EXPR$0 WHERE EMP.EMPNO < CASE WHEN CASE WHEN t1.c = 0 THEN FALSE WHEN t4.i IS NOT NULL THEN TRUE WHEN t1.ck < t1.c THEN NULL ELSE FALSE END = TRUE THEN 10 WHEN CASE WHEN t1.c = 0 THEN FALSE WHEN t4.i IS NOT NULL THEN TRUE WHEN t1.ck < t1.c THEN NULL ELSE FALSE END = FALSE THEN 20 ELSE 30 END
SELECT * FROM ((SELECT NAME FROM DEPT ORDER BY NAME) UNION ALL (SELECT NAME FROM DEPT ORDER BY NAME)) AS T1 ORDER BY NAME
SELECT * FROM ((SELECT NAME FROM DEPT ORDER BY NAME FETCH NEXT 0 ROWS ONLY) UNION ALL (SELECT NAME FROM DEPT ORDER BY NAME FETCH NEXT 0 ROWS ONLY)) AS T1 ORDER BY NAME FETCH NEXT 0 ROWS ONLY
SELECT 1 FROM (SELECT * FROM EMP AS EMP1 WHERE EMP1.DEPTNO > 7 AND EMP1.COMM = EMP1.DEPTNO AND EMP1.COMM + EMP1.DEPTNO > EMP1.COMM / 2) AS t2 INNER JOIN (SELECT * FROM (SELECT * FROM EMP AS EMP2 WHERE EMP2.SAL = EMP2.DEPTNO) AS t3 WHERE t3.DEPTNO > 7) AS t4 ON t2.DEPTNO = t4.DEPTNO
SELECT EMP2.EMPNO FROM EMP AS EMP2 LEFT JOIN (SELECT SINGLE_VALUE(EMP3.DEPTNO) AS $f0 FROM EMP AS EMP3 WHERE EMP3.EMPNO < 20) AS t7 ON TRUE LEFT JOIN (SELECT SINGLE_VALUE(EMP4.DEPTNO) AS $f0 FROM EMP AS EMP4 WHERE EMP4.EMPNO > 100) AS t10 ON TRUE WHERE t7.$f0 < t10.$f0 OR EMP2.SAL < 100
SELECT * FROM (SELECT NULL AS EXPR$0, NULL AS EXPR$1) AS t WHERE 1 = 0
SELECT t6.ENAME, MAX(t6.max1) FROM (SELECT EMP1.ENAME, MAX(EMP1.MGR) as max1 FROM EMP AS EMP1 GROUP BY EMP1.ENAME UNION ALL SELECT EMP2.ENAME, MAX(EMP2.MGR) as max1 FROM EMP AS EMP2 GROUP BY EMP2.ENAME) AS t6 GROUP BY t6.ENAME
SELECT 2, EMP1.DEPTNO, EMP1.JOB FROM EMP AS EMP1 UNION ALL SELECT 1, EMP2.DEPTNO, EMP2.JOB FROM EMP AS EMP2
SELECT 2, 3 FROM (SELECT 2 FROM EMP AS EMP1 UNION ALL SELECT 2 FROM EMP AS EMP2) AS t6
SELECT COUNT(*), CASE WHEN t2.expr1 THEN 11 ELSE t2.expr2 END FROM (SELECT EMP0.ENAME, EMP0.SAL < 11 AS expr1, -1 * EMP0.SAL AS expr2 FROM EMP AS EMP0) AS t2 RIGHT JOIN (SELECT BONUS0.ENAME FROM BONUS AS BONUS0) AS t3 ON t2.ENAME = t3.ENAME GROUP BY CASE WHEN t2.expr1 THEN 11 ELSE t2.expr2 END
SELECT * FROM (SELECT * FROM EMP AS EMP2 WHERE EMP2.DEPTNO = 10 UNION SELECT * FROM EMP AS EMP3 WHERE EMP3.DEPTNO = 20) AS t6 UNION ALL SELECT * FROM EMP AS EMP4 WHERE EMP4.DEPTNO = 30